--------------------------------------------------------------
-- 运动执行文件
-- 本文件负责机器人实际运动、吸盘开关、负载更新、隔板动作和栈板状态机调度。
---------------------------------------------------------------
-- 运动执行文件双语注释说明
-- 本文件是真正执行机器人动作的主文件：初始化、取料、放料、隔板取放、吸盘开关、payload更新、回程和状态机循环都在这里。
-- 关键输入是src3生成的CPoint：CPoint.Paras描述当前动作类型，CPoint.MotionPoint保存取料点/放料点/过渡点。
-- 常见条件说明：
-- 1. CPoint.Paras.Mode == MotionType.Norm：当前动作是普通箱子；MotionType.Part：当前动作是隔板。
-- 2. PalletNumber.Mode == WorkType.Pallet：码垛，把输送线箱子放到托盘；WorkType.Depallet：拆垛，把托盘箱子取走。
-- 3. CPoint.Paras.Sucker == -1：n吸n单放，通常一次吸多个箱子，然后按CIndex逐个放下。
-- 4. CIndex：当前正在处理第几个箱子/第几次放置；在n吸n单放中会影响剩余payload和释放哪一路吸盘。
-- 5. LDAcc/LDVel：带载速度参数；NLDAcc/NLDVel：空载速度参数；PlaceAcc/PlaceSpeed：贴近放置点的速度参数。
-- Motion execution file bilingual comment guide
-- This is the main runtime file that executes robot motion: initialization, pick, place, partition handling, sucker control, payload update, return motion, and state-machine loops.
-- The key input is CPoint generated by src3: CPoint.Paras describes the current process mode, while CPoint.MotionPoint stores pick/place/transition points.
-- Common condition meanings:
-- 1. CPoint.Paras.Mode == MotionType.Norm means the current motion is for normal boxes; MotionType.Part means the current motion is for partitions/interlayers.
-- 2. PalletNumber.Mode == WorkType.Pallet means palletizing from conveyor to pallet; WorkType.Depallet means depalletizing from pallet to output.
-- 3. CPoint.Paras.Sucker == -1 means multi-pick and single-place: the robot picks multiple boxes and releases them one by one according to CIndex.
-- 4. CIndex is the current box/place index. In multi-pick single-place, it controls remaining payload and which sucker channel should be released.
-- 5. LDAcc/LDVel are loaded motion parameters; NLDAcc/NLDVel are unloaded motion parameters; PlaceAcc/PlaceSpeed are used near the final placement point.
---------------------------------------------------------------
-- 主要数据来自global和src3生成的CPoint：
-- 1. CPoint.Paras保存当前动作类型、次数、吸盘模式、过渡点数量等工艺参数；
-- 2. CPoint.MotionPoint保存取料点、放料点、上方点、过渡点；
-- 3. CPoint.Paras.Mode决定当前动作是普通箱子还是隔板。
---------------------------------------------------------------
-- 局部常量
-- local constants
local mqttFunc = require("libplugin_eco")
local Dir = {
    Forward = 1, -- 正向运动
    -- forward motion
    Backward = -1 -- 反向运动
    -- backward motion
}
local LDAcc = ToolAccWithBox -- 带载加速度：抓着箱子或隔板移动时使用，来自界面参数。
-- loaded acceleration from the UI, used while carrying a box or partition
local LDVel = ToolSpeedWithBox -- 带载速度：抓着箱子或隔板移动时使用，来自界面参数。
-- loaded speed from the UI, used while carrying a box or partition
local NLDAcc = ToolAccWithoutBox -- 空载加速度：未抓取物料时使用，来自界面参数。
-- unloaded acceleration from the UI, used when not carrying material
local NLDVel = ToolSpeedWithoutBox -- 空载速度：未抓取物料时使用，来自界面参数。
-- unloaded speed from the UI, used when not carrying material
local LiftingPoint = {} -- 升降柱安全点位
-- lifting-column safety point
local PartPick = {
    pose = {}
} -- 隔板取料点
-- partition pick point
if HighLoadFunc == true then
    LiftingPoint = DeepCopy(LiftingSafetyPoint_HL)
else
    LiftingPoint = DeepCopy(LiftingSafetyPoint)
end
---------------------------------------------------------------
-- 局部变量
-- local variables
local SingleMotion = false -- 单次运动信号
-- single-motion trigger flag
local SyncSignal = false -- 同步信号
-- synchronization flag
local LiftingHeight = 0 -- 升降柱高度
-- lifting-column height
local SyncMotionVel = NLDVel -- 同步运动速度；无升降柱时直接使用空载速度，避免默认值过低导致动作变慢。
-- synchronized motion speed; without a lifting column, use unloaded speed to avoid a too-low default slowing the robot
local PrePallet = 1 -- 缠膜栈板号
-- pallet number used for wrapping flow
local PrePoseHeight = 0 -- 缠膜高度
-- wrapping height
---------------------------------------------------------------
-- 系统初始化
-- system initialization
---------------------------------------------------------------
-- 坐标系和工具坐标初始化。
-- initialize user frame and tool frame
-- 每次切换配方或初始化栈板时执行：
-- 1. 读取当前栈板的用户坐标、工具号、箱重和层数；
-- 2. 根据托盘高度修正用户坐标系的Z方向；
-- 3. 如果启用隔板，预先计算隔板取料点的笛卡尔位姿。
local function SetCoordinate(PalletNumber, PalletNum)
    PalletNumber.Layer = GetLayerCnt(PalletName, PalletNum)
    PalletNumber.Coordinate.UserNum = GetPalletUser(PalletName, PalletNum)
    local CTool = GetPalletTool(PalletName, ToolType.Conc)
    PalletNumber.Coordinate.ToolNum = CTool[1]
    PalletNumber.BoxProperty.BoxWeight = GetBoxLoad(PalletName, PalletNum)
    local PalletUser = CalcUser(PalletNumber.Coordinate.UserNum, 0, {0, 0, 0, 0, 0, 0})
    PalletUser[3] = PalletUser[3] + PalletNumber.ProcessNum.PalletHeight
    SetUser(PalletNumber.Coordinate.UserNum, PalletUser)
    HomePointPose = PositiveKin(HomePoint, {
        user = PalletNumber.Coordinate.UserNum,
        tool = PalletNumber.Coordinate.ToolNum
    })
    if (PalletNumber.Partition.Enable == true) then
        local ProjectType = CheckTableData(PalletNumber.TeachPoint.TeachPartitionPickPoint.joint)
        if (ProjectType == 1) then
            local PartPickJoint = {
                joint = {}
            }
            PartPickJoint.joint = DeepCopy(PalletNumber.TeachPoint.TeachPartitionPickPoint.joint)
            PartPick = PositiveKin(PartPickJoint)
        else
            PartPick.pose = DeepCopy(PalletNumber.TeachPoint.TeachPartitionPickPoint.pose)
            PartPick.pose[3] = PartPick.pose[3] - PalletNumber.ProcessNum.PalletHeight
        end
    end
end
---------------------------------------------------------------
-- 工作状态机初始化。
-- initialize the work state machine
-- 根据左右栈板使能状态、栈板到位状态和工作模式，决定当前工作站属于：
-- 1. 单输送单左栈板；
-- 2. 单输送单右栈板；
-- 3. 单输送双栈板；
-- 4. 双输送双栈板；
-- 5. 无栈板可运行。
local function InitFSM()
    -- 先读取左右栈板的使能状态；使能决定是否允许该侧进入状态机。
    GetEnableStatus()
    -- 左右栈板都使能：进入双栈板逻辑，再根据WorkingMode判断是单输送还是双输送。
    if (FirstPallet.StateValue.Enable == 1) and (SecondPallet.StateValue.Enable == 1) then
        ExecuteSafeModule(FirstPallet, SecondPallet)
        ExecuteSafeModule(SecondPallet, FirstPallet)
        Wait(Time.Thread.s0)
        -- 未启用人工确认按钮或处于仿真时，直接读取栈板传感器判断托盘是否在位。
        if (PalletBeInPlaceOKButton == false or SimulateMode == 1) then
            GetPalletStatus(FirstPallet)
            GetPalletStatus(SecondPallet)
            if (FirstPallet.State.Replace == false and SecondPallet.State.Replace == false) then
                TriLightStatus(FirstPallet, Light.Red.On)
                TriLightStatus(SecondPallet, Light.Red.On)
                Alarm("Palette absente !", ErrorMessage.Type.PalletErr)
            elseif (FirstPallet.State.Replace == false and SecondPallet.State.Replace == true) then
                TriLightStatus(FirstPallet, Light.Red.On)
                TriLightStatus(SecondPallet, Light.Init)
                Alarm("Palette absente !", ErrorMessage.Type.PalletErr)
            elseif (FirstPallet.State.Replace == true and SecondPallet.State.Replace == false) then
                TriLightStatus(FirstPallet, Light.Init)
                TriLightStatus(SecondPallet, Light.Red.On)
                Alarm("Palette absente !", ErrorMessage.Type.PalletErr)
            end

            Pallet = Left
        else
            Pallet = Idle
        end
        if WorkingMode == 0 then
            StateMachine = FSMType.SLR
            LogInfo("Mode convoyeur simple avec deux palettes initialisé !")
        else
            StateMachine = FSMType.DLR
            LogInfo("Mode double convoyeur avec deux palettes initialisé !")
        end
        SetCoordinate(SecondPallet, Right)
        SetCoordinate(FirstPallet, Left)
    else
        if (FirstPallet.StateValue.Enable == 1) then
            ExecuteSafeModule(FirstPallet, SecondPallet)
            GetPalletStatus(FirstPallet)
            if (FirstPallet.State.Replace == false and PalletBeInPlaceOKButton == false) then
                TriLightStatus(FirstPallet, Light.Red.On)
                TriLightStatus(SecondPallet, Light.Init)
                Alarm("Palette absente !", ErrorMessage.Type.PalletErr)
            end
            Pallet = Left
            StateMachine = FSMType.SL
            SetCoordinate(FirstPallet, Left)
            LogInfo("Mode convoyeur simple avec palette gauche initialisé !")
        elseif (SecondPallet.StateValue.Enable == 1) then
            ExecuteSafeModule(SecondPallet, FirstPallet)
            GetPalletStatus(SecondPallet)
            if (SecondPallet.State.Replace == false and PalletBeInPlaceOKButton == false) then
                TriLightStatus(FirstPallet, Light.Init)
                TriLightStatus(SecondPallet, Light.Red.On)
                Alarm("Palette absente !", ErrorMessage.Type.PalletErr)
            end
            Pallet = Right
            StateMachine = FSMType.SR
            SetCoordinate(SecondPallet, Right)
            LogInfo("Mode convoyeur simple avec palette droite initialisé !")
        else
            StateMachine = FSMType.IDLE
            TriLightStatus(FirstPallet, Light.Red.On)
            TriLightStatus(SecondPallet, Light.Red.On)
            Alarm("La palette n’est pas activée !", ErrorMessage.Type.PalletEnableErr)
        end
    end
end
--------------------------------------------------------------
-- 初始化数据恢复方式。
-- initialize power-loss data recovery mode
-- 断电恢复时可能从寄存器读取，也可能从控制器全局变量读取。
-- 如果相关保存值不存在，则写入默认结构，避免后续读取空表。
local function InitStorageMode()
    StorageMode = GetVal("PalletPowerDown")
    LogInfo("%s", (StorageMode == 0) and "Get working data from controller global variables!" or
        "Get working data from registers!")
    SetVal("PalletProjectName", PalletName)
    SetVal("LWorkState", StateType.Idle)
    SetVal("RWorkState", StateType.Idle)
    SetVal("ScriptState", true)
    if StorageMode == nil then
        StorageMode = 1
        SetVal("PalletTime", Time.Num)
        SetVal("PalletCapacity", Capacity.Num)
        SetVal("PalletWorkingDataA", FirstPallet.PalletNum)
        SetVal("PalletWorkingDataB", SecondPallet.PalletNum)
    end
    if (GetVal("PalletPartNumA") == nil) then
        SetVal("PalletPartNumA", FirstPallet.Partition.RePartNum)
    end
    if (GetVal("PalletPartNumB") == nil) then
        SetVal("PalletPartNumB", SecondPallet.Partition.RePartNum)
    end
    if (GetVal("PalletPartPlaceA") == nil) then
        SetVal("PalletPartPlaceA", FirstPallet.Partition.Place)
    end
    if (GetVal("PalletPartPlaceB") == nil) then
        SetVal("PalletPartPlaceB", SecondPallet.Partition.Place)
    end
end

---------------------------------------------------------------
-- 启动阶段同步两侧隔板数量。必须在ACK/隔板不足判断前执行，否则HMI仍会看到旧的0。
-- synchronize partition count for both sides during startup; must run before ACK/insufficient-partition checks, otherwise HMI may still show old zero values
local function SyncAllPartitionRemainBySensor(ForceLog)
    SyncPartitionRemainBySensor(FirstPallet, ForceLog)
    SyncPartitionRemainBySensor(SecondPallet, ForceLog)
end
---------------------------------------------------------------
-- 升降柱运动命令
-- lifting-column motion command
---------------------------------------------------------------
-----------------------------仿真------------------------------
-- 发送升降台升降动作消息
local function PublishLiftAction(Dest, UsedTime)
    local ActionStr = "[" .. Dest .. "," .. math.ceil(UsedTime) .. "]"
    mqttFunc.MQTTPublish(ConnectId, SimulateProcess.Id .. ':liftAction', ActionStr, 0, false)
end
---------------------------------------------------------------
-- 模拟升降台升降  
local function SimulateLiftingColumnMove(dest)
    LogInfo("Déplacement de la colonne élévatrice vers %s !", dest)
    LiftingColumn = SimulateProcess.LiftingColumn
    if LiftingColumn.LiftingHeight ~= dest then
        local UsedTime = math.floor(math.abs(LiftingColumn.LiftingHeight - dest) / LiftingColumn.Speed /
                                        SimulateProcess.SimulateSpeed * 1000)
        UsedTime = math.ceil(UsedTime / 100) * 100
        LiftingColumn.UsedTime = UsedTime * 1.0
        LiftingColumn.LiftingHeight = dest
        LogInfo("Déplacement de la colonne élévatrice vers %s, durée %s ms !", LiftingColumn.LiftingHeight, LiftingColumn.UsedTime)
        if (StateMachine == FSMType.DLR and Pallet ~= PrePallet) then
            PublishLiftAction(dest, LiftingColumn.UsedTime)
            -- PublishLiftAction(dest, UsedTime)
            -- PublishLiftAction(dest, UsedTime)
            -- Wait(100)
        else
            PublishLiftAction(dest, LiftingColumn.UsedTime)
            -- PublishLiftAction(dest, UsedTime)
            -- PublishLiftAction(dest, UsedTime)
            -- Wait(100)
        end
    end
end
---------------------------------------------------------------
-- 发送机械臂抓取动作消息  
local function PublishRobotAction()

    local BoxOnRobotStr = "["
    RobotContainer = SimulateProcess.BoxOnRobot

    if #RobotContainer == 0 then
        BoxOnRobotStr = BoxOnRobotStr .. "]"
    else
        for k, v in pairs(RobotContainer) do
            local BoxStr = "[" .. v.Id .. "," .. v.Layer .. "," .. v.Pallet .. "," .. v.State .. "," .. v.Child .. "]"
            if v == RobotContainer[#RobotContainer] then
                BoxOnRobotStr = BoxOnRobotStr .. BoxStr .. "]"
            else
                BoxOnRobotStr = BoxOnRobotStr .. BoxStr .. ","
            end
        end
    end

    Joint = GetAngle().joint

    local JointStr =
        "[" .. Joint[1] .. "," .. Joint[2] .. "," .. Joint[3] .. "," .. Joint[4] .. "," .. Joint[5] .. "," .. Joint[6] ..
            "]"
    local ActionStr = "[" .. BoxOnRobotStr .. "," .. JointStr .. "]"

    mqttFunc.MQTTPublish(ConnectId, SimulateProcess.Id .. ':robotAction', ActionStr, 0, false)
end
---------------------------------------------------------------
-- 发送机械臂抓取动作消息  
local function PublishPartitionAction(action, palletNum)
    local Joint = GetAngle().joint
    local JointStr =
        "[" .. Joint[1] .. "," .. Joint[2] .. "," .. Joint[3] .. "," .. Joint[4] .. "," .. Joint[5] .. "," .. Joint[6] ..
            "]"

    local ActionStr = "[" .. action .. "," .. JointStr .. "," .. palletNum .. "]"
    mqttFunc.MQTTPublish(ConnectId, SimulateProcess.Id .. ':partitionAction', ActionStr, 0, false)
end
---------------------------------------------------------------
-- 仿真模式下更新抓取状态。
-- update picked-object state in simulation mode
-- 真实生产中箱子状态由传感器和实际吸盘决定；仿真模式需要在脚本中手动更新箱子对象状态。
local function UpdatePickBoxState(PalletNumber, CPoint)
    local ContainerIn = SimulateProcess.BoxOnRobot
    local Conveyor = SimulateProcess.PresentConveyor

    if CPoint.Paras.Mode == MotionType.Norm then

        if PalletNumber.Mode == WorkType.Pallet then

            ContainerOut = Conveyor.Container

            Conveyor.PickDelayTime = Time.Pick.In
            if CPoint.Paras.Sucker > 0 then -- 吸多个箱子时
                for i = 1, math.ceil(0.5 * CPoint.Paras.Sucker) + 1 do
                    table.insert(ContainerIn, ContainerOut[i])
                end
                SimulateProcess.BoxCount = SimulateProcess.BoxCount + math.ceil(0.5 * CPoint.Paras.Sucker) + 1
            elseif CPoint.Paras.Sucker == -1 then -- 多吸单放
                for i = 1, math.abs(PalletSuckerFunction) do
                    table.insert(ContainerIn, ContainerOut[i])
                end
                SimulateProcess.BoxCount = SimulateProcess.BoxCount + PalletSuckerFunction
            else -- 吸单个箱子时
                table.insert(ContainerIn, ContainerOut[1])
                SimulateProcess.BoxCount = SimulateProcess.BoxCount + 1
            end

            for k, v in pairs(ContainerIn) do
                v:setState(1)
                v:setLayer(PalletNumber.PalletNum.LayerCount)
                v:setIndex(SimulateProcess.LayerBoxIndex)
                v:setPickIndex(SimulateProcess.PickIndex)
                v:setPallet(Pallet)
            end
        else
            local ContainerIn = SimulateProcess.BoxOnRobot
            local ConveyorNo = Pallet
            local BoxSize = PalletNumber.BoxProperty

            local BoxDirection
            if ConveyorNo == 0 then
                BoxDirection = FirstPalletBoxDirection
            else
                BoxDirection = SecondPalletBoxDirection
            end

            if CPoint.Paras.Sucker > 0 then ---吸多个箱子时
                for i = 1, math.ceil(0.5 * CPoint.Paras.Sucker) + 1 do
                    local B
                    if BoxDirection == 0 then
                        B = Box:new(0, Conveyor.Length - BoxSize.BoxWidth * (0.5 * i) - Conveyor.BoxInterval * (i - 1),
                            ConveyorNo, BoxSize.BoxWidth, BoxSize.BoxLength)
                    else
                        B = Box:new(0, Conveyor.Length - BoxSize.BoxWidth * (0.5 * i) - Conveyor.BoxInterval * (i - 1),
                            ConveyorNo, BoxSize.BoxLength, BoxSize.BoxWidth)
                    end

                    table.insert(ContainerIn, B)
                    B:setId(PalletNumber.PalletNum.NextBoxCount)
                    B:setState(1)
                    B:setLayer(PalletNumber.PalletNum.LayerCount)
                    B:setIndex(SimulateProcess.LayerBoxIndex)
                    B:setPickIndex(SimulateProcess.PickIndex)
                    B:setPallet(Pallet)
                    B:setChild(i - 1)
                end
                SimulateProcess.BoxCount = SimulateProcess.BoxCount + math.ceil(0.5 * CPoint.Paras.Sucker) + 1
                -- elseif CPoint.Paras.Sucker == -1 then
                --     for i = 1, PalletSuckerFunction do
                --         local B
                --         if BoxDirection == 0 then
                --             B = Box:new(0, Conveyor.Length - BoxSize.BoxWidth * (0.5 * i) - Conveyor.BoxInterval * (i - 1), ConveyorNo, BoxSize.BoxWidth, BoxSize.BoxLength)
                --         else
                --             B = Box:new(0, Conveyor.Length - BoxSize.BoxWidth * (0.5 * i) - Conveyor.BoxInterval * (i - 1), ConveyorNo, BoxSize.BoxLength, BoxSize.BoxWidth)
                --         end

                --         table.insert(ContainerIn, B)
                --         B:setId(PalletNumber.PalletNum.NextBoxCount)
                --         B:setState(1)
                --         B:setLayer(PalletNumber.PalletNum.LayerCount)
                --         B:setIndex(SimulateProcess.LayerBoxIndex)
                --         B:setPickIndex(SimulateProcess.PickIndex)
                --         B:setPallet(Pallet)
                --         B:setChild(i - 1)
                --     end
                --     SimulateProcess.BoxCount = SimulateProcess.BoxCount + PalletSuckerFunction
            else
                local B
                if BoxDirection == 0 then
                    B = Box:new(0, Conveyor.Length - 0.5 * BoxSize.BoxWidth, ConveyorNo, BoxSize.BoxWidth,
                        BoxSize.BoxLength)
                else
                    B = Box:new(0, Conveyor.Length - 0.5 * BoxSize.BoxLength, ConveyorNo, BoxSize.BoxLength,
                        BoxSize.BoxWidth)
                end
                table.insert(ContainerIn, B)

                B:setId(PalletNumber.PalletNum.NextBoxCount)
                B:setState(1)
                B:setLayer(PalletNumber.PalletNum.LayerCount)
                B:setIndex(SimulateProcess.LayerBoxIndex)
                B:setPickIndex(SimulateProcess.PickIndex)
                B:setPallet(Pallet)

                SimulateProcess.BoxCount = SimulateProcess.BoxCount + 1
            end
        end

        SimulateProcess.LayerBoxIndex = SimulateProcess.LayerBoxIndex + 1
        SimulateProcess.PickIndex = SimulateProcess.PickIndex + 1

        PublishRobotAction()
        -- PublishRobotAction()
        -- PublishRobotAction()
    else
        PublishPartitionAction(1, Pallet)
        -- PublishPartitionAction(1, Pallet)
        -- PublishPartitionAction(1, Pallet)
    end
end
---------------------------------------------------------------
-- 仿真模式下更新放置状态。
-- update placed-object state in simulation mode
-- 普通箱子放置后更新箱子在托盘上的位置；隔板放置后更新隔板对象状态。
local function UpdatePlaceBoxState(PalletNumber, CPoint)
    ContainerOut = SimulateProcess.BoxOnRobot
    local TempBoxOnRobot = DeepCopy(SimulateProcess.BoxOnRobot)
    if CPoint.Paras.Mode == MotionType.Norm then
        if PalletNumber.Mode == WorkType.Pallet then
            if PalletNumber == FirstPallet then
                ContainerIn = SimulateProcess.LeftPallet.Container
            else
                ContainerIn = SimulateProcess.RightPallet.Container
            end

            if CPoint.Paras.Sucker == -1 then
                local value = ContainerOut[1]
                ContainerIn[#ContainerIn + 1] = value.id
                value:setState(2)
                if SimulateProcess.SimulateSpeed == 1 then
                    SimulateProcess.Statistic.BoxCount = SimulateProcess.Statistic.BoxCount + 1
                end
            else
                for k, v in pairs(ContainerOut) do
                    ContainerIn[#ContainerIn + 1] = v.Id
                    v:setState(2)
                    if SimulateProcess.SimulateSpeed == 1 then
                        SimulateProcess.Statistic.BoxCount = SimulateProcess.Statistic.BoxCount + 1
                    end
                end
            end
            if CPoint.Paras.Sucker == -1 then
                SimulateProcess.BoxOnRobot = {SimulateProcess.BoxOnRobot[1]}
            end
        else
            SimulateProcess.PresentConveyor.PlaceDelayTime = Time.Place.In
            ContainerIn = SimulateProcess.PresentConveyor.Container
            for k, v in pairs(ContainerOut) do
                ContainerIn[#ContainerIn + 1] = v
                v:setState(0)
                if SimulateProcess.SimulateSpeed == 1 then
                    SimulateProcess.Statistic.BoxCount = SimulateProcess.Statistic.BoxCount + 1
                end
            end
        end

        LogInfo("%s", SimulateProcess.BoxOnRobot)
        PublishRobotAction()
        -- PublishRobotAction()
        -- PublishRobotAction()

        if PalletNumber.Mode == WorkType.Pallet then
            if CPoint.Paras.Sucker == -1 then
                table.remove(TempBoxOnRobot, 1)
                SimulateProcess.BoxOnRobot = TempBoxOnRobot
            else
                for i = 1, #ContainerOut do
                    table.remove(ContainerOut, 1)
                end
            end
        else
            for i = 1, #ContainerOut do
                table.remove(ContainerOut, 1)
            end
        end

    else
        PublishPartitionAction(0, Pallet)
        -- PublishPartitionAction(0, Pallet)
        -- PublishPartitionAction(0, Pallet)
    end
end
---------------------------------------------------------------
-- 检测传送带上是否还有箱子
local function CheckBoxOnConveyor(Conveyor, PalletNo)
    for k, v in pairs(Conveyor.Container) do
        if v.Pallet == PalletNo then
            return true
        end
    end

    return false
end
---------------------------------------------------------------
-- 统计仿真码垛节拍
local function StatisticLayerRate()
    if SimulateProcess.Statistic.TotalTime > 0 then
        SimulateProcess.Statistic.LayerRate = math.floor(SimulateProcess.Statistic.BoxCount /
                                                             SimulateProcess.Statistic.TotalTime * 1000 * 60 * 10)
    end
end
---------------------------------------------------------------
-- 统计单栈板耗时
local function StatisticPalletRate(PalletSide)
    if PalletSide.CanCount == 1 then
        SimulateProcess.Statistic.PalletNum = SimulateProcess.Statistic.PalletNum + 1
        SimulateProcess.Statistic.PalletRate = math.floor(SimulateProcess.Statistic.PalletTotalTime / 1000 / 60 /
                                                              SimulateProcess.Statistic.PalletNum * 10)
    end

    if SimulateProcess.SimulateSpeed > 1 then
        PalletSide.CanCount = 0
    else
        PalletSide.CanCount = 1
    end
end
---------------------------------------------------------------
----------------------------实际-------------------------------
-- 与升降轴建立通讯
local function InitLifting()
    if SimulateMode == 1 then
        if (Communication.Lifting.Mode == LiftingType.EWELLIX) then
            Communication.Lifting.CMaxDis = Communication.Lifting.Brand.EWELLIX.MaxDistance
        elseif (Communication.Lifting.Mode == LiftingType.GeMinG) then
            Communication.Lifting.CMaxDis = Communication.Lifting.Brand.GeMinG.MaxDistance
        elseif (Communication.Lifting.Mode == LiftingType.ZT3ILC) then
            Communication.Lifting.CMaxDis = Communication.Lifting.Brand.ZT3ILC.MaxDistance
        else
            Communication.Lifting.CMaxDis = Communication.Lifting.Brand.LINAK.MaxDistance
        end
        LogInfo("Mode simulation : CreateTcpConnection n’est pas exécuté !")
        return
    end

    local Err = 0
    local CurrentHeight
    local SwitchCommMode = {
        [LiftingType.EWELLIX] = function()
            Communication.Lifting.CMaxDis = Communication.Lifting.Brand.EWELLIX.MaxDistance
            Err, Communication.Lifting.Brand.EWELLIX.Tcp.Socket = TCPCreate(false,
                Communication.Lifting.Brand.EWELLIX.Tcp.Ip, Communication.Lifting.Brand.EWELLIX.Tcp.Port) -- 创建TCP客户端
            LogInfo("Tentative de connexion TCP à la colonne EWELLIX sur %s:%d !",
                Communication.Lifting.Brand.EWELLIX.Tcp.Ip, Communication.Lifting.Brand.EWELLIX.Tcp.Port)
        end,
        [LiftingType.GeMinG] = function()
            Communication.Lifting.CMaxDis = Communication.Lifting.Brand.GeMinG.MaxDistance
            Err, Communication.Lifting.Brand.GeMinG.ModbusRTU.Id = ModbusRTUCreate(
                Communication.Lifting.Brand.GeMinG.ModbusRTU.SlaveId,
                Communication.Lifting.Brand.GeMinG.ModbusRTU.BaudRate,
                Communication.Lifting.Brand.GeMinG.ModbusRTU.Parity,
                Communication.Lifting.Brand.GeMinG.ModbusRTU.DataBit,
                Communication.Lifting.Brand.GeMinG.ModbusRTU.StopBit)
            LogInfo("Tentative de connexion Modbus RTU à la colonne GeMinG avec l’identifiant esclave %d !",
                Communication.Lifting.Brand.GeMinG.ModbusRTU.SlaveId)
        end,
        [LiftingType.ZT3ILC] = function()
            Communication.Lifting.CMaxDis = Communication.Lifting.Brand.ZT3ILC.MaxDistance
            Err, Communication.Lifting.Brand.ZT3ILC.Modbus.Id = ModbusCreate(
                Communication.Lifting.Brand.ZT3ILC.Modbus.Ip, Communication.Lifting.Brand.ZT3ILC.Modbus.Port)
            LogInfo("Tentative de connexion Modbus TCP à la colonne ZT3ILC sur %s:%d !",
                Communication.Lifting.Brand.ZT3ILC.Modbus.Ip, Communication.Lifting.Brand.ZT3ILC.Modbus.Port)
        end,
        [LiftingType.LINAK] = function()
            Communication.Lifting.CMaxDis = Communication.Lifting.Brand.LINAK.MaxDistance
            Err, Communication.Lifting.Brand.LINAK.Modbus.Id =
                ModbusCreate(Communication.Lifting.Brand.LINAK.Modbus.Ip, Communication.Lifting.Brand.LINAK.Modbus.Port)
            LogInfo("Tentative de connexion Modbus TCP à la colonne LINAK sur %s:%d !",
                Communication.Lifting.Brand.LINAK.Modbus.Ip, Communication.Lifting.Brand.LINAK.Modbus.Port)
        end
    }
    local switch_mode = SwitchCommMode[Communication.Lifting.Mode]
    if switch_mode then
        switch_mode()
    else
        Alarm("CommMode est incorrect !", ErrorMessage.Type.WorkingDataErr)
    end
    if (Err == 0) then
        LogInfo("Initialisation de la communication terminée !")
    else
        Alarm("Échec de l’initialisation de la communication !", ErrorMessage.Type.LinkErr)
    end

    local SwitchCommInitMode = {
        [LiftingType.EWELLIX] = function()
            LogInfo("Création du client TCP réussie !")
            Err = EWLInit()
            Err, CurrentHeight = EWLGetPosition()
            if (Communication.Lifting.StopFlag == true) then
                Communication.Lifting.StopFlag = false
                Err, CurrentHeight = EWLGetPosition()
            end
        end,
        [LiftingType.GeMinG] = function()
            LogInfo("Création du client Modbus RTU réussie !")
            SV660CInit()
            SV660CEnable(1)
            CurrentHeight = SV660CGetPostion()[1]
            if CurrentHeight == nil then
                Err = 1
            else
                CurrentHeight = 0.1 * CurrentHeight
            end
        end,
        [LiftingType.ZT3ILC] = function()
            LogInfo("Création du client Modbus réussie !")
            ZC01Init()
            ZC01Enable(1)
            CurrentHeight = ZC01GetPostion()[1]
            if CurrentHeight == nil then
                Err = 1
            else
                CurrentHeight = ConvertFloat(CurrentHeight)
            end
        end,
        [LiftingType.LINAK] = function()
            LogInfo("Création du client Modbus réussie !")
            LINAKInit()
            CurrentHeight = LINAKGetPostion()
            if CurrentHeight == nil then
                Err = 1
            else
                CurrentHeight = 0.1 * CurrentHeight
            end
        end
    }

    local switch_init_mode = SwitchCommInitMode[Communication.Lifting.Mode]
    if switch_init_mode then
        switch_init_mode()
    else
        Alarm("switch_init_mode est incorrect !", ErrorMessage.Type.WorkingDataErr)
    end
    if Err == 0 then
        LogInfo("Connexion de communication réussie !")
    else
        Alarm("Échec de la connexion à la colonne élévatrice !", ErrorMessage.Type.LinkErr)
    end

    if (CurrentHeight == nil) then
        LogError("Hauteur de la colonne élévatrice : %s", tostring(CurrentHeight))
        Alarm("Erreur de données de la colonne élévatrice !", ErrorMessage.Type.LiftingDataErr)
    else
        LiftingHeight = math.ceil(CurrentHeight)
    end
    LogInfo("Initialisation de la colonne élévatrice réussie !")
end
---------------------------------------------------------------
-- 实时获取升降柱高度
local function GetLiftingHeight(CLH)
    local Err = 0
    local Res = 0
    local SwitchCommMode = {
        [LiftingType.EWELLIX] = function()
            Err, Res = EWLGetPosition()
            if ((Res >= CLH - 3) and (Res <= CLH + 3)) then
                SyncMotionVel = NLDVel
                LogInfo("Mouvement de la colonne élévatrice terminé !")
            end
        end,
        [LiftingType.GeMinG] = function()
            local RLH = math.ceil(CLH * 10)
            Res = SV660CGetPostion()
            if ((Res[1] <= RLH + 10) and (Res[1] >= RLH - 10)) then
                SyncMotionVel = NLDVel
                LogInfo("Mouvement de la colonne élévatrice terminé !")
            end
        end,
        [LiftingType.ZT3ILC] = function()
            Res = math.ceil(ZC01GetPostion())
            if ((Res <= math.ceil(CLH + 1)) and (Res >= math.ceil(CLH - 1))) then
                SyncMotionVel = NLDVel
                LogInfo("Mouvement de la colonne élévatrice terminé !")
            end
        end,
        [LiftingType.LINAK] = function()
            local RLH = math.ceil(CLH * 10)
            Res = LINAKGetPostion()
            if ((Res <= RLH + 30) and (Res >= RLH - 30)) then
                SyncMotionVel = NLDVel
                LogInfo("Mouvement de la colonne élévatrice terminé !")
            end
        end
    }
    local switch_mode = SwitchCommMode[Communication.Lifting.Mode]

    if (SyncSignal == true and SimulateMode == 0) then
        if switch_mode then
            switch_mode()
        else
            Alarm("CommMode est incorrect. Veuillez le vérifier !", ErrorMessage.Type.LiftingStateErr)
        end
    end
end
---------------------------------------------------------------
-- 等待升降柱到位运动
local function LiftingMotion(CLH)
    local Res = 0
    local Err = 0
    local StartTime = os.time()
    local Timeout = 60 -- 60s 超时报警
    local SwitchCommMode = {
        [LiftingType.EWELLIX] = function()
            repeat
                Err, Res = EWLGetPosition()
                if Err ~= 0 then
                    Alarm("État de la colonne élévatrice incorrect !", ErrorMessage.Type.LiftingStateErr)
                end
                if Communication.Lifting.StopFlag == true then
                    Communication.Lifting.StopFlag = false
                    EWLRun(CLH)
                end
                if (os.time() - StartTime > Timeout) then
                    Alarm("Délai d’attente du mouvement de la colonne élévatrice dépassé !", ErrorMessage.Type.LiftingStateErr)
                end
                LogInfo("La position de la colonne élévatrice est de %s mm ! ", Res)
                Wait(100)
            until ((Res <= CLH + 3) and (Res >= CLH - 3))
        end,
        [LiftingType.GeMinG] = function()
            local RLH = math.ceil(CLH * 10)
            repeat
                Res = SV660CGetPostion()
                if Communication.Lifting.StopFlag == true then
                    Communication.Lifting.StopFlag = false
                    SV660CRun(RLH)
                end
                if (os.time() - StartTime > Timeout) then
                    Alarm("Délai d’attente du mouvement de la colonne élévatrice dépassé !", ErrorMessage.Type.LiftingStateErr)
                end
                LogInfo("La position de la colonne élévatrice est de %s mm ! ", 0.1 * Res[1])
                Wait(100)
            until ((Res[1] <= RLH + 10) and (Res[1] >= RLH - 10))
        end,
        [LiftingType.ZT3ILC] = function()
            repeat
                Res = math.ceil(ZC01GetPostion())
                if Communication.Lifting.StopFlag == true then
                    Communication.Lifting.StopFlag = false
                    ZC01Init()
                    ZC01Run(math.ceil(CLH))
                end
                if (os.time() - StartTime > Timeout) then
                    Alarm("Délai d’attente du mouvement de la colonne élévatrice dépassé !", ErrorMessage.Type.LiftingStateErr)
                end
                LogInfo("La position de la colonne élévatrice est de %s mm ! ", Res)
                Wait(100)
            until ((Res <= math.ceil(CLH + 1)) and (Res >= math.ceil(CLH - 1)))
        end,
        [LiftingType.LINAK] = function()
            local RLH = math.ceil(CLH * 10)
            repeat
                Res = LINAKGetPostion()
                if Communication.Lifting.StopLiftingFlag == true then
                    Communication.Lifting.StopLiftingFlag = false
                    LINAKInit()
                    LINAKRun(RLH)
                end
                Wait(100)
            until ((Res <= RLH + 30) and (Res >= RLH - 30))
        end
    }
    local switch_mode = SwitchCommMode[Communication.Lifting.Mode]
    if switch_mode then
        switch_mode()
        LogInfo("Mouvement de la colonne élévatrice terminé !")
    else
        Alarm("CommMode est incorrect. Veuillez le vérifier !", ErrorMessage.Type.LiftingStateErr)
    end
end
---------------------------------------------------------------
-- 调整升降柱高度
local function AdjustLiftingHeight(CLH)
    if (PalletLiftingFunction == true) and (math.abs(CLH - LiftingHeight) > 1) then
        LogInfo("La distance relative de déplacement de la colonne élévatrice est de %s mm !", math.abs(CLH - LiftingHeight))
        SyncSignal = true
        if (math.abs(CLH - LiftingHeight) == Communication.Lifting.CMaxDis) then
            SyncMotionVel = 2
        else
            SyncMotionVel = math.ceil(10 * (1 - math.abs(CLH - LiftingHeight) / Communication.Lifting.CMaxDis))
        end
        LogInfo("Le rapport de vitesse colonne/robot est de %s !", SyncMotionVel)
        LiftingHeight = CLH
        Communication.Lifting.TimesPerHour = Communication.Lifting.TimesPerHour + 1
        LogInfo("La position cible de la colonne élévatrice est de %s mm !", CLH)
        if (SimulateMode == 1) then
            SimulateLiftingColumnMove(CLH)
            LogInfo("Mode simulation : moveTo_absolutePosition, %s", CLH)
        else
            local SwitchCommMode = {
                [LiftingType.EWELLIX] = function()
                    EWLRun(CLH)
                    EWLGetPosition()
                end,
                [LiftingType.GeMinG] = function()
                    SV660CRun(math.ceil(CLH * 10))
                end,
                [LiftingType.ZT3ILC] = function()
                    ZC01Run(CLH)
                end,
                [LiftingType.LINAK] = function()
                    LINAKRun(math.ceil(CLH * 10))
                end
            }
            local switch_mode = SwitchCommMode[Communication.Lifting.Mode]
            if switch_mode then
                switch_mode()
            else
                Alarm("SwitchCommMode est incorrect. Veuillez le vérifier !", ErrorMessage.Type.LiftingStateErr)
            end
        end
    else
        SyncSignal = false
        SyncMotionVel = NLDVel
    end
end
---------------------------------------------------------------
-- 运动命令
---------------------------------------------------------------
-- 运动到安全原点
local function RobotGoHome()
    local CPose = GetPose()
    local CJoint = GetAngle()
    if (ResetPathFunc == true) then
        if (CPose.pose[1] > 400) then
            HomeTransPointL.joint[6] = 0.5 * CJoint.joint[6]
            MovL(HomeTransPointL, {a = NLDAcc * 0.25, v = NLDVel * 0.25, cp = 100})
        elseif (CPose.pose[1] < -400) then
            HomeTransPointR.joint[6] = 0.5 * CJoint.joint[6]
            MovL(HomeTransPointR, {a = NLDAcc * 0.25, v = NLDVel * 0.25, cp = 100})
        end
    end
    MovJ(HomePoint, {a = NLDAcc * 0.25, v = NLDVel * 0.25, cp = 100})
    LogInfo("Retour du robot à la position d’origine réussi !")
    local value1 = GetHoldRegs(1, 5007, 1, "U16")
    print(value1)
    local value2 = GetHoldRegs(1, 5009, 1, "U16")
    print(value2)
end
---------------------------------------------------------------
-- 获取点位模式
-- get point mode
local function GetPointMode(CMode, CType)
    if CMode == MotionType.Part then
        ErrorMessage.PointInfo.Type = CType.Part
    else
        ErrorMessage.PointInfo.Type = CType.Norm
    end
end
---------------------------------------------------------------
-- 获取点位类型
local function GetPointType(CPoint)
    if CPoint.Paras.ErrIndex <= PointType.Trans.Index.E then
        GetPointMode(CPoint.Paras.Mode, PointType.Trans.Cfg)
        return
    end

    if CPoint.Paras.ErrIndex == PointType.Pick.Index.A then
        GetPointMode(CPoint.Paras.Mode, PointType.Pick.Cfg)
        return
    end

    if CPoint.Paras.ErrIndex == PointType.PickOffset.Index.A then
        GetPointMode(CPoint.Paras.Mode, PointType.PickOffset.Cfg)
        return
    end

    if CPoint.Paras.ErrIndex >= PointType.Place.Index.A and CPoint.Paras.ErrIndex <= PointType.Place.Index.D then
        GetPointMode(CPoint.Paras.Mode, PointType.Place.Cfg)
        return
    end

    if CPoint.Paras.ErrIndex >= PointType.PlaceOffset.Index.A and CPoint.Paras.ErrIndex <= PointType.PlaceOffset.Index.D then
        GetPointMode(CPoint.Paras.Mode, PointType.PlaceOffset.Cfg)
        return
    end

    if CPoint.Paras.ErrIndex >= PointType.Insert.Index.A then
        GetPointMode(CPoint.Paras.Mode, PointType.Insert.Cfg)
        return
    end
end
---------------------------------------------------------------
-- 获取点位信息
local function GetPointInfo(PalletNumber, CPoint)
    local LayerNum = 0
    GetPointType(CPoint)
    if PalletNumber.Mode == WorkType.Pallet then
        if (PalletNumber.ProcessNum.BoxCount >= PalletNumber.PalletNum.LayerBoxNum) and
            (PalletNumber.PalletNum.LayerBoxNum > 0) and (CPoint.Paras.Mode == MotionType.Norm) then
            ErrorMessage.PointInfo.Layer = PalletNumber.PalletNum.LayerCount + 1
        else
            ErrorMessage.PointInfo.Layer = PalletNumber.PalletNum.LayerCount
        end
    else
        local LocalLayerBoxNum = GetOddBoxCnt(PalletName, PalletNumber.Pallet, PalletNumber.PalletNum.LayerCount)
        local TempBoxNum = PalletNumber.PalletNum.LayerBoxNum - LocalLayerBoxNum
        if (PalletNumber.ProcessNum.BoxCount <= TempBoxNum) and (TempBoxNum > 0) then
            ErrorMessage.PointInfo.Layer = PalletNumber.PalletNum.LayerCount - 1
        else
            ErrorMessage.PointInfo.Layer = PalletNumber.PalletNum.LayerCount
        end
    end
    if ErrorMessage.PointInfo.Type == 5 or ErrorMessage.PointInfo.Type == 6 then
        ErrorMessage.PointInfo.Index = PalletNumber.PalletNum.NextBoxCount
    else
        for i = 1, (ErrorMessage.PointInfo.Layer - 1) do
            LayerNum = LayerNum + GetOddBoxCnt(PalletName, PalletNumber.Pallet, i)
        end
        ErrorMessage.PointInfo.Index = PalletNumber.PalletNum.NextBoxCount - LayerNum
    end
    ErrorMessage.PointInfo.PalletNum = PalletNumber.Pallet
    LogError("Point inaccessible — palette : %d, type : %d, couche : %d, index : %d", ErrorMessage.PointInfo.PalletNum,
        ErrorMessage.PointInfo.Type, ErrorMessage.PointInfo.Layer, ErrorMessage.PointInfo.Index)
    Alarm("CPoint inaccessible !", ErrorMessage.Type.PointErr)
end
---------------------------------------------------------------
-- 计算码垛数量
local function GetPalletIndex(PalletNumber)
    if PalletNumber.ProcessNum.BoxCount > PalletNumber.PalletNum.LayerBoxNum then
        if PalletNumber.PalletNum.LayerBoxNum > 0 then
            PalletNumber.PalletNum.LayerCount = PalletNumber.PalletNum.LayerCount + 1
        end
        PalletNumber.PalletNum.LayerBoxNum = PalletNumber.PalletNum.LayerBoxNum +
                                                 GetOddBoxCnt(PalletName, PalletNumber.Pallet,
                PalletNumber.PalletNum.LayerCount)
        if SimulateMode == 1 then
            SimulateProcess.LayerNum = SimulateProcess.LayerNum + 1
            StatisticLayerRate()
        end
    end

    PalletNumber.PalletNum.RemainBoxNum = PalletNumber.PalletNum.LayerBoxNum - PalletNumber.ProcessNum.BoxCount
end
---------------------------------------------------------------
-- 托盘完成后清除原始ACK锁存和运行许可。
-- 新托盘可以复位工作数据，但必须重新按ACK后Replace才会再次变为true。
local function ResetPalletAck(PalletNumber)
    if PalletBeInPlaceOKButton ~= true then
        return
    end

    PalletNumber.State.InPlaceOK = false
    PalletNumber.State.Replace = false
    PalletNumber.State.StateReady = false
    SignalReady = false
    if PalletNumber.Pallet == Pallet then
        Pallet = Idle
    end

    LogInfo("Palette %s en attente d’un nouvel ACK.",
        (PalletNumber.Pallet == Left) and "gauche" or "droite")
end
---------------------------------------------------------------
-- 计算放置箱子数量
local function CalPlaceBoxNum(PalletNumber, CPoint)
    if (PalletNumber.PalletNum.NextBoxCount <= PalletNumber.ProcessNum.TotalBoxNum) then
        PalletNumber.ProcessNum.BoxCount = PalletNumber.PalletNum.NextBoxCount -- 托盘已放置箱体的数量
        PalletNumber.PalletNum.NextBoxCount = PalletNumber.PalletNum.NextBoxCount + 1 -- 托盘下一个放置箱体的数量
        PalletNumber.ProcessNum.TotalBoxNum = GetBoxCnt(PalletName, PalletNumber.Pallet)
        if PalletNumber.ProcessNum.BoxCount > PalletNumber.ProcessNum.TotalBoxNum then
            LogWarn("BoxCount est incorrect !")
            PalletNumber.ProcessNum.BoxCount = PalletNumber.ProcessNum.TotalBoxNum
            PalletNumber.PalletNum.NextBoxCount = PalletNumber.ProcessNum.TotalBoxNum + 1
        end
        GetPalletIndex(PalletNumber)
        if (CPoint.Paras.Sucker > 0) then
            PalletNumber.PalletNum.AddBoxCount = PalletNumber.PalletNum.AddBoxCount +
                                                     math.ceil(CPoint.Paras.Sucker * 0.5)
        end

        CommitPalletNum(PalletNumber) -- 上传已有料箱层数、剩余料箱数
        PlaceCountPallet(PalletNumber) -- 调用放置计数程序
    end
    -- 判断托盘是否已满载。当托盘计数大于单侧箱体的总数视为满载
    if (PalletNumber.PalletNum.NextBoxCount > PalletNumber.ProcessNum.TotalBoxNum) then
        if (PalletNumber.Partition.Enable == true) then
            if (PalletNumber.Partition.Last == false) and (PalletNumber.Partition.Layer[PalletNumber.Layer + 1] == 1) then
                PalletNumber.Partition.Last = true
                LogInfo("Début du mouvement de l’intercalaire de la dernière couche !")
                return
            else
                PalletNumber.Partition.Last = false
            end
        end
        PalletNumber.State.Done = true -- 将满载布尔变量置为true
        PalletNumber.StateValue.Status = StateType.Stop
        CommitPalletStatus(PalletNumber)
        ResetPalletAck(PalletNumber)
        if (StateMachine ~= FSMType.DLR) or
            ((StateMachine == FSMType.DLR) and (FirstPallet.State.Done == true) and (SecondPallet.State.Done == true)) then
            PalletNumber.State.StateReady = false
        end
        if SimulateMode == 1 then
            LogInfo(" La palette %s est pleine !", (Pallet == Left) and 'Left' or 'Right')
            if FirstPallet.State.Done then
                StatisticPalletRate(SimulateProcess.LeftPallet)
            end
            if SecondPallet.State.Done then
                StatisticPalletRate(SimulateProcess.RightPallet)
            end
            if PalletNumber.State.StateReady == false then
                LogInfo("Non prêt !")
                SimulateProcess.LayerNum = 1 -- 当前操作层数
                SimulateProcess.LayerBoxIndex = 0 -- 当前层的箱子索引
                SimulateProcess.LayerBoxNum = 0 -- 首层到当前层搬运的箱子数
                SimulateProcess.PickIndex = 1 -- 吸取索引
            end
        end
        LogInfo("La palette %s est terminée !", (PalletNumber.Pallet == Left) and "gauche" or "droite")
    end
end
---------------------------------------------------------------
-- 计算拆垛数量
local function GetDePalletIndex(PalletNumber)
    local LocalLayerBoxNum = GetOddBoxCnt(PalletName, PalletNumber.Pallet, PalletNumber.PalletNum.LayerCount)
    local TempBoxNum = PalletNumber.PalletNum.LayerBoxNum - LocalLayerBoxNum
    PalletNumber.PalletNum.RemainBoxNum = PalletNumber.ProcessNum.BoxCount - TempBoxNum
    if PalletNumber.ProcessNum.BoxCount <= TempBoxNum then
        PalletNumber.PalletNum.LayerBoxNum = PalletNumber.PalletNum.LayerBoxNum - LocalLayerBoxNum
        if PalletNumber.PalletNum.LayerBoxNum > 0 then
            PalletNumber.PalletNum.LayerCount = PalletNumber.PalletNum.LayerCount - 1
            PalletNumber.PalletNum.RemainBoxNum = GetOddBoxCnt(PalletName, PalletNumber.Pallet,
                PalletNumber.PalletNum.LayerCount)
            if SimulateMode == 1 then
                StatisticLayerRate()
            end
        end
    end
end
---------------------------------------------------------------
-- 计算拆垛箱子数量
local function CalDePalletPlaceBoxNum(PalletNumber, CPoint)
    if (PalletNumber.PalletNum.NextBoxCount > 0) then
        PalletNumber.ProcessNum.BoxCount = PalletNumber.PalletNum.NextBoxCount - 1 -- 托盘已放置箱体的数量
        PalletNumber.PalletNum.NextBoxCount = PalletNumber.ProcessNum.BoxCount -- 托盘下一个放置箱体的数量
        if (PalletNumber.ProcessNum.BoxCount < 0) then
            LogWarn("BoxCount est incorrect !")
            PalletNumber.ProcessNum.BoxCount = 0
            PalletNumber.PalletNum.NextBoxCount = 0
        end
        GetDePalletIndex(PalletNumber)
        if (CPoint.Paras.Sucker > 0) then
            PalletNumber.PalletNum.AddBoxCount = PalletNumber.PalletNum.AddBoxCount -
                                                     math.ceil(CPoint.Paras.Sucker * 0.5)
        end

        CommitPalletNum(PalletNumber) -- 上传已有料箱层数、剩余料箱数
        PlaceCountPallet(PalletNumber) -- 调用放置计数程序
    end
    if (PalletNumber.PalletNum.NextBoxCount <= 0) then -- 判断托盘是否已满载。当托盘计数大于单侧箱体的总数视为满载
        if (PalletNumber.Partition.Enable == true) then
            if (PalletNumber.Partition.Last == false) and (PalletNumber.Partition.Layer[1] == 1) then
                PalletNumber.Partition.Last = true
                LogInfo("Début du mouvement de l’intercalaire de la dernière couche !")
                return
            else
                PalletNumber.Partition.Last = false
            end
        end
        PalletNumber.State.Done = true -- 将满载布尔变量置为true
        PalletNumber.StateValue.Status = StateType.Stop
        CommitPalletStatus(PalletNumber)
        ResetPalletAck(PalletNumber)
        if (StateMachine ~= FSMType.DLR) or
            ((StateMachine == FSMType.DLR) and (FirstPallet.State.Done == true) and (SecondPallet.State.Done == true)) then
            PalletNumber.State.StateReady = false
        end
        if SimulateMode == 1 then
            LogInfo(" La palette %s est vide !", (Pallet == Left) and 'Left' or 'Right')
            if FirstPallet.State.Done == true then
                StatisticPalletRate(SimulateProcess.LeftPallet)
            end

            if SecondPallet.State.Done == true then
                StatisticPalletRate(SimulateProcess.RightPallet)
            end
        end
        LogInfo("La palette %s est terminée !", (PalletNumber.Pallet == Left) and "gauche" or "droite")
    end
end
---------------------------------------------------------------
-- 吸盘控制
---------------------------------------------------------------
-- 按吸盘数量批量控制通用输出。
-- PortCfg提供A/B/C/D四路端口，Num决定本次实际打开或关闭几路。
local function SuckerControll(PortCfg, State, Num)
    local DIPorts = {PortCfg.A, PortCfg.B, PortCfg.C, PortCfg.D}
    for i = 1, Num do
        IORes(PortCfg.Mode, DIPorts[i], State)
    end
end
---------------------------------------------------------------
-- 吸盘安全信号
local function SuckerSafeIO(State)
    if (SPortCfg.Enable == true or Communication.Lifting.Mode == LiftingType.EWELLIX) then
        IORes(SPortCfg.Port.Mode, SPortCfg.Port.A, State)
    end
end
---------------------------------------------------------------
-- 检测吸盘状态
local function VerifySuckerDO(PortCfg, DOIndex, ExpectedState)
    local ActualState = CheckDORes(PortCfg.Mode, DOIndex)
    if (ActualState ~= ExpectedState) then
        Alarm("Sucker DO" .. tostring(DOIndex) .. " state mismatch!", ErrorMessage.Type.WorkingDataErr)
    end
end
---------------------------------------------------------------
-- 初始化吸盘
local function InitSucker()
    DropDete(FirstPallet, DropType.Prep)
    DropDete(SecondPallet, DropType.Prep)

    if (PalletSuckerFunction == SuckerCfg.Type.SSingle) then
        local ErrA = 0
        local ErrB = 0
        SetTool485(Communication.Sucker.Tcp.BaudRate, Communication.Sucker.Tcp.Parity, Communication.Sucker.Tcp.StopBit)
        ErrA, Communication.Sucker.Tcp.Socket = TCPCreate(false, Communication.Sucker.Tcp.Ip,
            Communication.Sucker.Tcp.Port) -- 创建TCP客户端
        ErrB = TCPStart(Communication.Sucker.Tcp.Socket, 5) -- 建立TCP连接
        if ErrA ~= 0 or ErrB ~= 0 then
            Alarm("Échec de l’initialisation de la ventouse !", ErrorMessage.Type.IPErr)
        else
            LogInfo("Création du client TCP de la ventouse réussie !")
        end
    else
        SuckerControll(SuckerCfg.Port, OFF, math.abs(PalletSuckerFunction))
        if (PalletSuckerFunction ~= SuckerCfg.Type.SSingle) then
            SuckerSafeIO(OFF)
        end
        if PartCfg.Enable then
            IORes(PartCfg.Port.Mode, PartCfg.Port.A, OFF)
        end

        if SuckerCfg.Dete.VacuumBreak.Enable == 1 then
            SuckerControll(SuckerCfg.Dete.VacuumBreak, OFF, math.abs(PalletSuckerFunction))
        end
    end
    LogInfo("Initialisation de la ventouse réussie !")
end
---------------------------------------------------------------
-- 计算偏心工具。
-- 多吸盘抓多个箱子时，实际负载质心会偏离工具中心。
-- 这里根据吸盘模式和当前仍然吸住的箱子数量，选择对应偏心工具数据，用于SetPayload。
local function CalcEccTool(PalletNumber, Sucker, BoxNum)
    local CTool = {}
    local PlaceNum = math.abs(PalletSuckerFunction)
    if (PlaceNum == BoxNum) then
        CTool = CalcTool(PalletNumber.Coordinate.ToolNum, 0, {0, 0, 0, 0, 0, 0})
    else
        local Ecc = {}
        local EccTool = {}
        local EccData = {}
        Ecc, EccTool, EccData = GetPalletTool(PalletName, ToolType.Ecc)
        local EccLength = {}

        if (Sucker ~= -1) then
            EccLength = (PlaceNum - 1) * EccTool[2][1]
        else
            EccLength = (PlaceNum - 1) * EccTool[3][1]
        end

        local SwitchSucker = {
            [SuckerCfg.Type.Double] = function()
                EccTool[2][1] = EccTool[1][1] + EccLength * math.cos(EccTool[1][6] / 180 * math.pi)
                EccTool[2][2] = EccTool[1][2] + EccLength * math.sin(EccTool[1][6] / 180 * math.pi)
                CTool = DeepCopy(EccTool[2])
            end,
            [SuckerCfg.Type.Triple] = function()
                CTool = CalcTool(PalletNumber.Coordinate.ToolNum, 0, {0, 0, 0, 0, 0, 0})
            end,
            [SuckerCfg.Type.Quadruple] = function()
                CTool = CalcTool(PalletNumber.Coordinate.ToolNum, 0, {0, 0, 0, 0, 0, 0})
            end
        }

        local switch_mode = SwitchSucker[PlaceNum]
        if switch_mode then
            switch_mode()
        else
            Alarm("Le type de ventouse est incorrect !", ErrorMessage.Type.WorkingDataErr)
        end
    end

    LogInfoTable("CTool:", CTool)
    return CTool
end

---------------------------------------------------------------
-- 打开吸盘。
-- 普通箱体仅通过SuckerCfg.Port配置控制真空，并保留阶梯式payload预载。
-- 隔板仅通过PartCfg.Port配置控制独立真空，不使用普通箱吸盘或释放信号。
---------------------------------------------------------------
local function OpenSucker(PalletNumber, CPoint, CIndex)
    local BoxNum = 0
    local CTool = {}

    local SwitchOpenSucker = {
        [MotionType.Norm] = function()
            if (PalletNumber.Mode == WorkType.Pallet) then
                -- 本项目固定：单吸单放。
                BoxNum = 1
                CTool = CalcEccTool(PalletNumber, CPoint.Paras.Sucker, BoxNum)

                local BoxWeight = PalletNumber.BoxProperty.BoxWeight
                local Weight30 = ToolWeight + 0.30 * BoxWeight
                local Weight50 = ToolWeight + 0.50 * BoxWeight
                local Weight75 = ToolWeight + 0.75 * BoxWeight
                local FullWeight = ToolWeight + BoxWeight
                local PayloadCenter = {CTool[1], CTool[2], 0.5 * (CTool[3] + PalletNumber.BoxProperty.BoxHigh)}

                -- 打开前端配置的主真空输出。
                IORes(SuckerCfg.Port.Mode, SuckerCfg.Port.A, ON)
                Wait(50)

                SetPayload(Weight30, PayloadCenter)
                LogInfo("Précharge de prise à 30 %% après activation du vide. Poids : %s", Weight30)
                Wait(50)

                SetPayload(Weight50, PayloadCenter)
                LogInfo("Précharge de prise à 50 %% après activation du vide. Poids : %s", Weight50)
                Wait(50)

                SetPayload(Weight75, PayloadCenter)
                LogInfo("Précharge de prise à 75 %% après activation du vide. Poids : %s", Weight75)

                -- 前面已等待150ms，总真空建立时间保持1000ms。
                Wait(850)
                VerifySuckerDO(SuckerCfg.Port, SuckerCfg.Port.A, ON)
                SuckerSafeIO(OFF)

                SetPayload(FullWeight, PayloadCenter)
                LogInfo("Charge utile de prise à 100 %% après la temporisation du vide. Poids : %s", FullWeight)
                Wait(Time.Pick.In)
            else
                Alarm("Cette fonction OpenSucker personnalisée est réservée au mode de palettisation !", ErrorMessage.Type.WorkingDataErr)
            end
        end,

        [MotionType.Part] = function()
            -- 隔板必须使用前端配置的独立PartCfg端口（现场为DO16）。
            if (PartCfg.Enable ~= true) then
                Alarm("La ventouse d’intercalaire n’est pas activée !", ErrorMessage.Type.WorkingDataErr)
                return
            end

            IORes(PartCfg.Port.Mode, PartCfg.Port.A, ON)
            Wait(Time.Pick.In)

            CTool = CalcEccTool(PalletNumber, CPoint.Paras.Sucker, PalletSuckerFunction)
            SetPayload(PalletNumber.ProcessNum.PartitionWeight + ToolWeight, {CTool[1], CTool[2], 0.5 * CTool[3]})
        end
    }

    local switch_mode = SwitchOpenSucker[CPoint.Paras.Mode]
    if switch_mode then
        switch_mode()
        LogInfo("Activation de la ventouse réussie !")
    else
        Alarm("Erreur OpenSucker. Veuillez vérifier la ventouse !", ErrorMessage.Type.WorkingDataErr)
    end
end
---------------------------------------------------------------
-- 关闭吸盘 / 释放物料。
-- 普通箱：关闭配置的真空输出；如前端启用释放信号，则只通过
-- SuckerCfg.Dete.VacuumBreak配置输出破真空，绝不写死具体DO号。
-- 隔板：只关闭PartCfg独立真空并等待自然飘落，不使用破真空。
---------------------------------------------------------------
local function CloseSucker(PalletNumber, CPoint, CIndex)
    local CTool = {}
    if ((CPoint.Paras.Sucker ~= -1) or (CPoint.Paras.Sucker == -1 and CIndex == PalletSuckerFunction)) then
        CTool = CalcTool(PalletNumber.Coordinate.ToolNum, 0, {0, 0, 0, 0, 0, 0})
    else
        CTool = CalcEccTool(PalletNumber, CPoint.Paras.Sucker, CIndex)
    end

    local Weight = (PalletSuckerFunction - CIndex) * PalletNumber.BoxProperty.BoxWeight + ToolWeight
    local ReleasePayloadDelay = 50
    local PayloadUpdated = false

    local function UpdatePayloadAfterRelease()
        if PayloadUpdated == false then
            SetPayload(Weight, {CTool[1], CTool[2], 0.5 * CTool[3]})
            LogInfo("Charge utile après relâchement : %s", Weight)
            PayloadUpdated = true
        end
    end

    local function WaitReleaseAndUpdatePayload()
        local DelayTime = ReleasePayloadDelay
        if Time.Place.In < DelayTime then
            DelayTime = Time.Place.In
        end
        if DelayTime > 0 then
            Wait(DelayTime)
        end
        UpdatePayloadAfterRelease()
        if Time.Place.In > DelayTime then
            Wait(Time.Place.In - DelayTime)
        end
    end

    local function SetSingleReleaseOutput(CIndex, State)
        local Port = SuckerCfg.Dete.VacuumBreak
        if CIndex == 1 then
            IORes(Port.Mode, Port.A, State)
        elseif CIndex == 2 then
            IORes(Port.Mode, Port.B, State)
        elseif CIndex == 3 then
            IORes(Port.Mode, Port.C, State)
        elseif CIndex == 4 then
            IORes(Port.Mode, Port.D, State)
        end
    end

    local SwitchCloseSucker = {
        [MotionType.Norm] = function()
            local ReleaseEnabled = (SuckerCfg.Dete.VacuumBreak.Enable == 1)

            if (CPoint.Paras.Sucker == -1) then
                if (PalletNumber.Mode == WorkType.Pallet) then
                    -- 多吸单放：只关闭当前箱对应的真空路。
                    if CIndex == 1 then
                        IORes(SuckerCfg.Port.Mode, SuckerCfg.Port.A, OFF)
                    elseif CIndex == 2 then
                        IORes(SuckerCfg.Port.Mode, SuckerCfg.Port.B, OFF)
                    elseif CIndex == 3 then
                        IORes(SuckerCfg.Port.Mode, SuckerCfg.Port.C, OFF)
                    elseif CIndex == 4 then
                        IORes(SuckerCfg.Port.Mode, SuckerCfg.Port.D, OFF)
                    end
                    SuckerSafeIO(ON)

                    if ReleaseEnabled then
                        SetSingleReleaseOutput(CIndex, ON)
                        WaitReleaseAndUpdatePayload()
                        SetSingleReleaseOutput(CIndex, OFF)
                        return
                    end
                else
                    SuckerControll(SuckerCfg.Port, OFF, math.abs(PalletSuckerFunction))
                    SuckerSafeIO(ON)

                    if ReleaseEnabled then
                        SuckerControll(SuckerCfg.Dete.VacuumBreak, ON, math.abs(PalletSuckerFunction))
                        WaitReleaseAndUpdatePayload()
                        SuckerControll(SuckerCfg.Dete.VacuumBreak, OFF, math.abs(PalletSuckerFunction))
                        return
                    end
                end
            elseif (PalletSuckerFunction == SuckerCfg.Type.SSingle and CPoint.Paras.Sucker == 0) then
                TCPWrite(Communication.Sucker.Tcp.Socket, Communication.Sucker.Command.VacuumOff)
            else
                local ReleaseNum = math.ceil(0.5 * CPoint.Paras.Sucker) + 1
                SuckerControll(SuckerCfg.Port, OFF, ReleaseNum)
                SuckerSafeIO(ON)

                if ReleaseEnabled then
                    SuckerControll(SuckerCfg.Dete.VacuumBreak, ON, ReleaseNum)
                    WaitReleaseAndUpdatePayload()
                    SuckerControll(SuckerCfg.Dete.VacuumBreak, OFF, ReleaseNum)
                    return
                end
            end

            -- 未启用释放信号时，只等待物料自然脱离并更新payload。
            WaitReleaseAndUpdatePayload()
        end,

        [MotionType.Part] = function()
            -- 隔板仅使用独立PartCfg真空（现场为DO16），不使用破真空。
            if (PartCfg.Enable ~= true) then
                Alarm("La ventouse d’intercalaire n’est pas activée !", ErrorMessage.Type.WorkingDataErr)
                return
            end

            IORes(PartCfg.Port.Mode, PartCfg.Port.A, OFF)
            Wait(Time.Place.In)
            UpdatePayloadAfterRelease()
        end
    }

    local switch_mode = SwitchCloseSucker[CPoint.Paras.Mode]
    if switch_mode then
        switch_mode()
        LogInfo("Désactivation de la ventouse réussie !")
    else
        Alarm("Erreur CloseSucker. Veuillez vérifier la ventouse !", ErrorMessage.Type.WorkingDataErr)
    end
end
---------------------------------------------------------------
-- 初始化三色灯状态
local function InitLight()
    if (StateMachine == FSMType.SLR or StateMachine == FSMType.DLR) then
        TriLightStatus(FirstPallet, Light.Green.On)
        TriLightStatus(SecondPallet, Light.Green.On)
    elseif (StateMachine == FSMType.SL) then
        TriLightStatus(FirstPallet, Light.Green.On)
        TriLightStatus(SecondPallet, Light.Init)
    else
        TriLightStatus(FirstPallet, Light.Init)
        TriLightStatus(SecondPallet, Light.Green.On)
    end
    LogInfo("Initialisation du voyant tricolore réussie !")
end
---------------------------------------------------------------
-- 初始化，复位信号、复位程序数据
local function InitPallet()
    if BuzzerFunction == true then
        DO(BuzzerIO, OFF) -- 关闭蜂鸣器
        LogInfo("Initialisation de l’avertisseur sonore réussie !")
    end
    InitSucker() -- 吸盘初始化
    InitLight() -- 三色灯初始化
    if (PalletLiftingFunction == true) then
        InitLifting() -- 与升降轴建立TCP通讯
    end
    RobotGoHome()
end
---------------------------------------------------------------
-- 缠膜功能
local function FilmMotion()
    local DestPose = {}
    local JointAngle = {}
    if FilmFunction == true then
        if (DI(FilmDI) == ON) and (FilmDone == true) and (CheckDORes(SuckerCfg.Port.Mode, SuckerCfg.Port.A) == OFF) and
            (CheckDORes(SuckerCfg.Port.Mode, SuckerCfg.Port.B) == OFF) then
            FilmDone = false
            JointAngle = DeepCopy(LiftingPoint)
            MovJ(JointAngle, {a = NLDAcc, v = NLDVel, cp = 100})
            DestPose = GetPose()
            if PrePoseHeight > DestPose.pose[3] then
                AdjustLiftingHeight(math.floor(PrePoseHeight - DestPose.pose[3]))
            end

            if PrePallet == 1 then
                JointAngle.joint[1] = 180
            elseif PrePallet == 2 then
                JointAngle.joint[1] = 0
            else
                Alarm("La palette est incorrecte !", ErrorMessage.Type.WorkingDataErr)
            end
            MovJ(JointAngle, {a = NLDAcc, v = NLDVel, cp = 100})
            LogInfo("Début de FilmMotion !")
        end
        if (DI(FilmDI) == OFF) and (FilmDone == false) then
            MovJ(LiftingPoint, {a = NLDAcc, v = NLDVel, cp = 100})
            DestPose = GetPose()
            if PrePoseHeight > DestPose.pose[3] then
                AdjustLiftingHeight(math.floor(PrePoseHeight - DestPose.pose[3]))
            end
            FilmDone = true
            LogInfo("Fin de FilmMotion !")
        end
    end
end
---------------------------------------------------------------
-- J1安全分支归一化：本项目禁止J1继续向负方向绕到操作员侧
-- 现场安全分支：当前隔板放置后约-50°，安全点90°，取货点约150°
-- 因此目标J1如果被逆解成-210°/-270°，需要转换成等效的150°/90°
local J1SafeMin = -60
local J1SafeMax = 200

local function NormalizeJ1ToSafeBranch(j1)
    if j1 == nil then
        return j1
    end

    while j1 < J1SafeMin do
        j1 = j1 + 360
    end

    while j1 > J1SafeMax do
        j1 = j1 - 360
    end

    if (j1 < J1SafeMin) or (j1 > J1SafeMax) then
        LogError("La cible J1 est hors de la branche sûre : %s", tostring(j1))
        Alarm("La cible J1 est hors de la branche sûre !", ErrorMessage.Type.PointErr)
    end

    return j1
end

-- J6软件限位比“无限等效角度归一化”更窄。
-- 控制器只接受软件限位范围内的等效腕部角度。
-- 现场曾出现当前J6约为-329°，旧逻辑把下一个目标换算成-443°的情况；
-- 虽然数学上等效，但已经超过J6软件限位，所以这里必须先限制到安全范围内。
local J6SoftMin = -360
local J6SoftMax = 360

local function NormalizeJ6ToValidRange(j6, UseCurrentNearest)
    if j6 == nil then
        return j6
    end

    local RefJ6 = j6
    if UseCurrentNearest == true then
        local CurrentJoint = GetAngle().joint
        if (CurrentJoint ~= nil) and (CurrentJoint[6] ~= nil) then
            RefJ6 = CurrentJoint[6]
        end
    end

    local BestJ6 = nil
    local BestDiff = nil

    -- 遍历附近的等效角度，选择落在软件限位内的候选值。
    -- UseCurrentNearest=true时，优先选择最接近当前J6的等效角，减少腕部突然大幅旋转。
    -- UseCurrentNearest=false时，尽量保留示教或计算得到的原始角度。
    for k = -3, 3 do
        local Candidate = j6 + 360 * k
        if (Candidate >= J6SoftMin) and (Candidate <= J6SoftMax) then
            local Diff = math.abs(Candidate - RefJ6)
            if (BestJ6 == nil) or (Diff < BestDiff) then
                BestJ6 = Candidate
                BestDiff = Diff
            end
        end
    end

    if BestJ6 ~= nil then
        return BestJ6
    end

    LogError("La cible J6 dépasse la limite logicielle après normalisation : %s", tostring(j6))
    Alarm("La cible J6 dépasse la limite logicielle !", ErrorMessage.Type.PointErr)
    return j6
end

local function NormalizeJointForSafeBranch(Point, NormalizeJ6)
    local P = DeepCopy(Point)

    if (P ~= nil) and (P.joint ~= nil) then
        P.joint[1] = NormalizeJ1ToSafeBranch(P.joint[1])
        -- 始终保证J6落在软件限位内。
        -- NormalizeJ6=true只表示优先选择更接近当前J6的等效角，不代表允许越过软件限位。
        P.joint[6] = NormalizeJ6ToValidRange(P.joint[6], NormalizeJ6 == true)
    end

    return P
end

local function SafeMovJ(Point, Option, NormalizeJ6)
    local P = NormalizeJointForSafeBranch(Point, NormalizeJ6)
    MovJ(P, Option)
end

local function SafeMovL(Point, Option, NormalizeJ6)
    local P = NormalizeJointForSafeBranch(Point, NormalizeJ6)
    MovL(P, Option)
end

-- Side Pick专用运动保护：
-- 除了归一化J1/J6，还检查当前J1到目标J1的单段变化。
-- 超过150°时禁止执行，避免机器人从侧取区域绕入另一侧操作员区域。
local SidePickJ1MaxSegment = 150

local function ValidateSidePickSegment(TargetPoint, MotionName)
    if (TargetPoint == nil) or (TargetPoint.joint == nil) then
        LogError("Point Side Pick invalide : %s", tostring(MotionName))
        Alarm("Point Side Pick invalide !", ErrorMessage.Type.PointErr)
        return false
    end

    local CurrentJoint = GetAngle().joint
    if (CurrentJoint == nil) or (CurrentJoint[1] == nil) then
        LogError("Impossible de lire J1 avant le mouvement Side Pick : %s", tostring(MotionName))
        Alarm("Lecture J1 Side Pick impossible !", ErrorMessage.Type.PointErr)
        return false
    end

    local DeltaJ1 = math.abs(TargetPoint.joint[1] - CurrentJoint[1])
    if DeltaJ1 > SidePickJ1MaxSegment then
        LogError("Mouvement Side Pick interdit (%s) : J1 actuel=%s, J1 cible=%s, delta=%s",
            tostring(MotionName), tostring(CurrentJoint[1]), tostring(TargetPoint.joint[1]), tostring(DeltaJ1))
        Alarm("Trajectoire Side Pick vers zone opérateur interdite !", ErrorMessage.Type.PointErr)
        return false
    end

    return true
end

local function SafeSideMovJ(Point, Option, NormalizeJ6, MotionName)
    local P = NormalizeJointForSafeBranch(Point, NormalizeJ6)
    if ValidateSidePickSegment(P, MotionName) ~= true then
        return false
    end
    MovJ(P, Option)
    return true
end

local function SafeSideMovL(Point, Option, NormalizeJ6, MotionName)
    local P = NormalizeJointForSafeBranch(Point, NormalizeJ6)
    if ValidateSidePickSegment(P, MotionName) ~= true then
        return false
    end
    MovL(P, Option)
    return true
end

---------------------------------------------------------------
-- 过渡点运动
---------------------------------------------------------------
-- TransMotion速度说明
-- TransMotion用于过渡点前进/后退。速度参数由调用方传入：带载路径通常传LDAcc/LDVel，空载回程通常传NLDAcc/NLDVel。
-- 这里不要再写死30/20/10等速度，否则界面设置为100也不会真正生效。
-- TransMotion speed note
-- TransMotion is used for forward/backward transition points. Speed is passed by the caller: loaded paths normally use LDAcc/LDVel, unloaded return paths normally use NLDAcc/NLDVel.
-- Do not hard-code 30/20/10 here; otherwise UI speed values such as 100 will not actually take effect.
---------------------------------------------------------------
local function TransMotion(CPoint, CDir, Acc, Vel)
    local SD = 1
    local ED = CPoint.Paras.TransNum
    if (CDir == Dir.Backward) then
        SD = CPoint.Paras.TransNum
        ED = 1
    end

    if (CPoint.Paras.Mode == MotionType.Norm) and (CPoint.Paras.SidePick ~= true) then
        for i = SD, ED, CDir do
            if PalletObstacleFunc == 1 then
                MovL(CPoint.MotionPoint[i], {a = Acc, v = Vel, cp = 100})
            else
                MovJ(CPoint.MotionPoint[i], {a = Acc, v = Vel, cp = 100})
            end
        end
        return true
    end

    for i = SD, ED, CDir do
        local TPoint = CPoint.MotionPoint[i]
        if (CDir == Dir.Forward) and (CPoint.ForwardMotionPoint ~= nil) and (type(CPoint.ForwardMotionPoint[i]) == "table") then
            TPoint = CPoint.ForwardMotionPoint[i]
        elseif (CDir == Dir.Backward) and (CPoint.BackwardMotionPoint ~= nil) and (type(CPoint.BackwardMotionPoint[i]) == "table") then
            TPoint = CPoint.BackwardMotionPoint[i]
        end
        if (type(TPoint) == "table") then
            local TAcc = Acc
            local TVel = Vel
            if (TAcc == nil) then
                TAcc = NLDAcc
            end
            if (TVel == nil) then
                TVel = NLDVel
            end
            if (CDir == Dir.Backward) then
                if (CPoint.Paras.Mode == MotionType.Part) then
                    SafeMovL(TPoint, {a = TAcc, v = TVel, cp = 100}, true)
                else
                    if SafeSideMovJ(TPoint, {a = TAcc, v = TVel, cp = 100}, true,
                        (CDir == Dir.Forward) and "transition aller" or "transition retour") ~= true then
                        return false
                    end
                end
            else
                if (CPoint.Paras.Mode == MotionType.Part) then
                    SafeMovL(TPoint, {a = TAcc, v = TVel * 0.5, cp = 100}, false)
                else
                    if SafeSideMovJ(TPoint, {a = TAcc, v = TVel, cp = 100}, true,
                        (CDir == Dir.Forward) and "transition aller" or "transition retour") ~= true then
                        return false
                    end
                end
            end
        end
    end
    return true
end

---------------------------------------------------------------
-- 升降柱运动
local function SyncMotion(CLH)
    if (SimulateMode == 1) then
        SyncSignal = false
        if SimulateProcess.LiftingColumn.UsedTime ~= 0 then
            -- if (CLH < 1) then
            Wait(math.ceil(SimulateProcess.LiftingColumn.UsedTime))
            SimulateProcess.LiftingColumn.UsedTime = 0
            -- else
            --     Wait(100)
            -- end
        end
        return
    end
    if (SyncSignal == true) then
        SyncSignal = false
        LiftingMotion(CLH)
    end
end
---------------------------------------------------------------
-- 获取隔板待机点关节，供回程过渡点和待机点共用同一个J6
local function GetPartitionStandbyJoint(CPoint)
    local Standy = {
        pose = {}
    }
    Standy.pose = DeepCopy(CPoint.Paras.Standy.pose)
    Standy.pose[3] = Standy.pose[3] - CPoint.Paras.LH

    local ErrId, StandyJoint = InverseKin(Standy)
    if (ErrId ~= 0) or (StandyJoint == nil) or (StandyJoint.joint == nil) then
        Alarm("Échec de la cinématique inverse pour la position d’attente de l’intercalaire !", ErrorMessage.Type.PointErr)
    end

    return StandyJoint
end

---------------------------------------------------------------

---
-- 待机位置运动
local function StandyMotion(PalletNumber, CPoint)
    if (PalletNumber.State.StateReady == false) and (LiftingHeight > 1) then
        SafeMovL(CPoint.Paras.Standy, {a = NLDAcc, v = NLDVel, cp = 100}, false)
        AdjustLiftingHeight(Home)
        SyncMotion(Home)
    elseif (CPoint.Paras.Mode == MotionType.Part) then
        -- 隔板回待机点：优先使用src3提供的待机点 关节，保证与回程过渡点的终点J6一致
        if (CPoint.StandyMotionPoint ~= nil) and (CPoint.StandyMotionPoint.joint ~= nil) then
            SafeMovJ(CPoint.StandyMotionPoint, {a = NLDAcc, v = NLDVel, cp = 100}, true)
        else
            SafeMovJ(GetPartitionStandbyJoint(CPoint), {a = NLDAcc, v = NLDVel, cp = 100}, true)
        end
    else
        if CPoint.Paras.SidePick == true then
            if SafeSideMovL(CPoint.MotionPoint[7], {a = NLDAcc, v = NLDVel, cp = 100}, false,
                "retour au-dessus prise") ~= true then
                return
            end
        else
            MovJ(CPoint.MotionPoint[7], {a = NLDAcc, v = NLDVel, cp = 100})
        end
    end
end
---------------------------------------------------------------
-- 隔板放置后先回安全点，避免直接回待机点时J1转到操作员侧危险区域
local function PartitionGoSafePoint(CPoint, UseGlobalPartSafePoint, KeepCurrentJ6)
    local SafePoint = nil

    if (UseGlobalPartSafePoint ~= true) and (CPoint.MotionPoint[7] ~= nil) and (CPoint.MotionPoint[7].joint ~= nil) then
        -- 隔板运动自身/下一笔隔板动作：优先使用src3计算出来的MotionPoint[7]隔板安全点
        SafePoint = DeepCopy(CPoint.MotionPoint[7])
    else
        -- 兜底才使用全局隔板安全点PartSafePoint
        SafePoint = DeepCopy(PartSafePoint)
    end

    -- 默认保持当前J6，避免刚离开放置点就发生腕部旋转。
    -- 但普通箱子最后一箱后准备进入隔板时，需要直接去“下一笔隔板安全点”的完整关节，
    -- 这样下一笔隔板动作不会在安全点再额外转一次J6。
    if KeepCurrentJ6 ~= false then
        local CurrentJoint = GetAngle().joint
        if (SafePoint.joint ~= nil) and (CurrentJoint ~= nil) then
            SafePoint.joint[6] = CurrentJoint[6]
        end
    end

    SafeMovJ(SafePoint, {a = NLDAcc, v = NLDVel, cp = 100}, true)
end

-- 获取队列里的下一笔隔板动作；用于普通箱子最后一箱后直接去下一笔隔板安全点
local function GetNextPartitionMotion(CQueue)
    if (CQueue == nil) or (CQueue:IsEmpty() == true) then
        return nil
    end

    local NextPoint = CQueue:Peek()
    if (NextPoint ~= nil) and (NextPoint.Paras ~= nil) and (NextPoint.Paras.Mode == MotionType.Part) then
        return NextPoint
    end

    return nil
end
---------------------------------------------------------------
-- 隔板余量传感器检测：放置隔板后检测料仓是否还有隔板
-- DI = ON/1：认为料仓有隔板，恢复默认隔板数量，并写入Modbus/SetVal
-- DI ON/1 means partitions are available; restore the default partition count and write it to Modbus/SetVal
-- DI = OFF/0：认为料仓无隔板，将剩余隔板数量置为0，并写入Modbus/SetVal
-- DI OFF/0 means no partitions are available; set remaining partition count to 0 and write it to Modbus/SetVal
local function CheckPartitionRemainSensor(PalletNumber, CPoint)
    if (CPoint == nil) or (CPoint.Paras == nil) then
        return
    end

    if (CPoint.Paras.Mode ~= MotionType.Part) or (PalletNumber.Mode ~= WorkType.Pallet) then
        return
    end

    if (PartSensorCfg == nil) or (PartSensorCfg.Enable ~= true) then
        return
    end

    if (PartSensorCfg.Port == nil) or (PartSensorCfg.Port.A == nil) then
        LogWarn("L’entrée DI du capteur de présence des intercalaires n’est pas configurée !")
        return
    end

    if SimulateMode == 1 then
        return
    end

    local DelayTime = PartSensorCfg.DelayTime or 0
    local SensorState = CheckDIRes(PartSensorCfg.Port.Mode, PartSensorCfg.Port.A)

    if DelayTime > 0 then
        Wait(DelayTime)
        SensorState = CheckDIRes(PartSensorCfg.Port.Mode, PartSensorCfg.Port.A)
    end

    if SensorState == ON then
        PalletNumber.Partition.RePartNum = PalletNumber.ProcessNum.PartitionNum
        WritePartNum(PalletNumber)
        LogInfo(
            "Le capteur de présence des intercalaires DI%s est actif. Restauration du nombre d’intercalaires par défaut et écriture Modbus : %s.",
            tostring(PartSensorCfg.Port.A), tostring(PalletNumber.Partition.RePartNum))
    else
        PalletNumber.Partition.RePartNum = 0
        WritePartNum(PalletNumber)
        LogWarn("Le capteur de présence des intercalaires DI%s est inactif. Le nombre d’intercalaires restants est défini à 0 et écrit dans Modbus.",
            tostring(PartSensorCfg.Port.A))
    end
end
---------------------------------------------------------------
-- 隔板动作开始前检测：如果传感器已经确认无隔板，则不再继续执行取隔板动作
local function CheckPartitionRemainBeforeMotion(PalletNumber, CPoint)
    if (CPoint == nil) or (CPoint.Paras == nil) then
        return true
    end

    if (CPoint.Paras.Mode ~= MotionType.Part) or (PalletNumber.Mode ~= WorkType.Pallet) then
        return true
    end

    if (PartSensorCfg == nil) or (PartSensorCfg.Enable ~= true) then
        return true
    end

    if (PartSensorCfg.Port == nil) or (PartSensorCfg.Port.A == nil) then
        LogWarn("L’entrée DI du capteur de présence des intercalaires n’est pas configurée !")
        return true
    end

    if SimulateMode == 1 then
        return true
    end

    local DelayTime = PartSensorCfg.DelayTime or 0
    local SensorState = CheckDIRes(PartSensorCfg.Port.Mode, PartSensorCfg.Port.A)

    if DelayTime > 0 then
        Wait(DelayTime)
        SensorState = CheckDIRes(PartSensorCfg.Port.Mode, PartSensorCfg.Port.A)
    end

    if SensorState == OFF then
        PalletNumber.Partition.RePartNum = 0
        WritePartNum(PalletNumber)
        LogWarn("Le capteur de présence des intercalaires DI%s est inactif avant le mouvement. Le nombre d’intercalaires restants est défini à 0.",
            tostring(PartSensorCfg.Port.A))
        Alarm("Le magasin d’intercalaires est vide !", ErrorMessage.Type.PartErr)
        return false
    end

    -- 当前传感器检测到有隔板时，强制恢复默认数量，并写入Modbus/SetVal。
    -- 这样即使之前被写成0，补充隔板后也能恢复显示值。
    if PalletNumber.Partition.RePartNum ~= PalletNumber.ProcessNum.PartitionNum then
        PalletNumber.Partition.RePartNum = PalletNumber.ProcessNum.PartitionNum
        WritePartNum(PalletNumber)
        LogInfo(
            "Le capteur de présence des intercalaires DI%s est actif avant le mouvement. Restauration du nombre d’intercalaires par défaut et écriture Modbus : %s.",
            tostring(PartSensorCfg.Port.A), tostring(PalletNumber.Partition.RePartNum))
    end

    return true
end
---------------------------------------------------------------
-- 更新隔板数据
local function UpdatePartData(PalletNumber, CPoint)
    if (CPoint.Paras.Mode == MotionType.Part) then
        -- 使用隔板余量传感器时，隔板数量不再由动作次数维护。
        -- 放置后的数量更新只由 CheckPartitionRemainSensor() 负责：
        -- DI=ON 恢复默认数量，DI=OFF 将 RePartNum 写为0。
        if (PalletNumber.Mode == WorkType.Pallet) and (PartSensorCfg ~= nil) and (PartSensorCfg.Enable == true) then
            return
        end

        if (PalletNumber.Mode == WorkType.Pallet) then
            if (PalletNumber.Partition.RePartNum <= 0) then
                -- 仿真模式，不需要隔板数量报警
                if SimulateMode == 1 then
                    PalletNumber.Partition.RePartNum = PalletNumber.ProcessNum.PartitionNum
                    return
                end
                Alarm("Le magasin d’intercalaires est vide !", ErrorMessage.Type.PartErr)
                PalletNumber.Partition.RePartNum = PalletNumber.ProcessNum.PartitionNum
                WritePartNum(PalletNumber)
            end
        else
            if (PalletNumber.Partition.RePartNum >= PalletNumber.ProcessNum.PartitionNum) then
                -- 仿真模式，不需要隔板数量报警
                if SimulateMode == 1 then
                    PalletNumber.Partition.RePartNum = 0
                    return
                end
                Alarm("Le magasin d’intercalaires est plein !", ErrorMessage.Type.PartErr)
                PalletNumber.Partition.RePartNum = 0
                WritePartNum(PalletNumber)
            end
        end
    end
end
---------------------------------------------------------------
-- 更新工作数据
local function UpdateData(PalletNumber, CPoint)
    if (PalletNumber.Partition.Enable == true) then
        if (PalletNumber.Pallet == Left) then
            SetVal("PalletPartPlaceA", CPoint.Paras.Mode)
        else
            SetVal("PalletPartPlaceB", CPoint.Paras.Mode)
        end
    end
    if (CPoint.Paras.Mode == MotionType.Norm) or (PalletNumber.Partition.Last == true) then
        if (PalletNumber.Mode == WorkType.Pallet) then
            CalPlaceBoxNum(PalletNumber, CPoint) -- 执行托盘码垛计数
        else
            CalDePalletPlaceBoxNum(PalletNumber, CPoint) -- 执行托盘拆垛计数
        end

    end
    if (CPoint.Paras.Mode == MotionType.Part) then
        -- 使用隔板余量传感器时，放置隔板后不再按动作次数修改 RePartNum。
        -- RePartNum 只由传感器决定：DI=ON恢复默认值，DI=OFF写0。
        if (PartSensorCfg ~= nil) and (PartSensorCfg.Enable == true) and (PalletNumber.Mode == WorkType.Pallet) then
            return
        end

        -- 非传感器模式保留原有计数逻辑，避免影响未启用隔板传感器的项目。
        if (PalletNumber.Mode == WorkType.Pallet) then
            PalletNumber.Partition.RePartNum = PalletNumber.Partition.RePartNum - 1
        else
            PalletNumber.Partition.RePartNum = PalletNumber.Partition.RePartNum + 1
        end
        WritePartNum(PalletNumber)
    end
end
---------------------------------------------------------------
-- 根据栈板类型调整隔板点位（右栈板需要在0用户坐标系下向X方向平移1000mm）
local function GetAdjustedPartitionPoint(PalletNumber, BasePoint)
    local AdjustedPoint = DeepCopy(BasePoint)
    if PalletNumber.Pallet == 1 then
        AdjustedPoint.pose[1] = AdjustedPoint.pose[1] - 1000
    end
    return AdjustedPoint
end
---------------------------------------------------------------
-- MotionPoint[index]:
-- 1~5:过渡点（示教），6:取料（示教），7：取料上方点（自动生成），8~11：放置点（自动生成）
-- 12~15：放料上方点（自动生成），16~19：放料偏移点（自动生成）
---------------------------------------------------------------
-- 执行单笔点位运动。
-- CPoint由src3生成，是一次完整取放动作的数据包。
-- 码垛模式下流程大致为：取料上方点 -> 取料点 -> 打开吸盘 -> 去程过渡点 -> 放置点 -> 关闭吸盘 -> 回程过渡点 -> 待机点。
-- 拆垛模式下流程相反：先从托盘取料，再放到输送线或取料点。
-- CPoint.Paras.Mode决定普通箱子和隔板走不同路径。
local function PTPMotion(PalletNumber, CPoint, CQueue)
    local CPose = {
        pose = {}
    }
    -- 隔板取料后抬升参数：速度使用界面空载速度，避免10/10硬限速。
    -- partition lift-after-pick parameters; use UI unloaded speed to avoid the hard-coded 10/10 speed limit
    local PartSlowLiftHeight = 200
    local PartSlowLiftAcc = NLDAcc
    local PartSlowLiftVel = NLDVel
    -- 隔板放置完成后，先垂直抬升100mm，再走回程过渡点
    local PartPlaceLiftHeight = 100

    if (PalletNumber.Mode == WorkType.Pallet) then
        -- 码垛模式：从输送线或隔板料仓取料，再放到托盘。
        Wait(Time.Pick.Pre)
        if (CPoint.Paras.Mode == MotionType.Part) then
            -- 隔板码垛：DI21余量检查已在PreMotion中、Pop队列前完成。
            -- Partition palletizing: DI21 remain check is completed in PreMotion before queue Pop.
            local CPartPick = DeepCopy(PartPick)
            CPartPick.pose[3] = CPartPick.pose[3] - CPoint.Paras.LH + PalletNumber.ProcessNum.PartitionHeight *
                                    PalletNumber.Partition.RePartNum
            SafeMovJ(CPoint.MotionPoint[7], {a = NLDAcc, v = SyncMotionVel, cp = 100}, true)
            SyncMotion(CPoint.Paras.LH)

            local CPartPickLift = DeepCopy(CPartPick)
            CPartPickLift.pose[3] = CPartPickLift.pose[3] + PartSlowLiftHeight
            MovL(CPartPickLift, {a = NLDAcc, v = NLDVel, cp = 100})

            MovL(CPartPick, {a = NLDAcc, v = NLDVel, stopcond = "AI(1) <= 0.5"}) -- 运动到抓取点，速度使用界面空载速度

            -- MovL(CPartPick, { a = NLDAcc, v = NLDVel, cp = 100 }) --运动到抓取点

            OpenSucker(PalletNumber, CPoint)
            Wait(500)
            if SimulateMode == 1 then
                UpdatePickBoxState(PalletNumber, CPoint)
            end

            -- 取到隔板后：先垂直抬升 200 mm，速度使用界面空载速度
            -- after picking a partition: lift vertically by 200 mm using UI unloaded speed
            local CPartPickLift = DeepCopy(CPartPick)
            CPartPickLift.pose[3] = CPartPickLift.pose[3] + PartSlowLiftHeight
            MovL(CPartPickLift, {a = PartSlowLiftAcc, v = PartSlowLiftVel, cp = 100})

        else
            -- 普通箱子码垛：从箱子取料点取箱，再进入放置流程。
            if ((SingleMotion == false) or (SyncSignal == true) or
                (StateMachine == FSMType.DLR and PalletNumber.Pallet ~= PrePallet)) then
                SingleMotion = true
                if CPoint.Paras.SidePick == true then
                    if SafeSideMovJ(CPoint.MotionPoint[7], {a = NLDAcc, v = SyncMotionVel, cp = 100}, true,
                        "approche au-dessus prise") ~= true then
                        return
                    end
                else
                    MovJ(CPoint.MotionPoint[7], {a = NLDAcc, v = SyncMotionVel, cp = 100})
                end
                SyncMotion(CPoint.Paras.LH)
            end
            if CPoint.Paras.SidePick == true then
                if SafeSideMovL(CPoint.MotionPoint[6], {a = NLDAcc, v = NLDVel, cp = 100}, true,
                    "descente prise") ~= true then
                    return
                end
            else
                MovL(CPoint.MotionPoint[6], {a = NLDAcc, v = NLDVel, cp = 100}) -- 运动到抓取点
            end
            OpenSucker(PalletNumber, CPoint)
            if SimulateMode == 1 then
                UpdatePickBoxState(PalletNumber, CPoint)
            end
            if CPoint.Paras.SidePick == true then
                if SafeSideMovL(CPoint.MotionPoint[7], {a = LDAcc, v = LDVel, cp = 100}, true,
                    "remontée au-dessus prise") ~= true then
                    return
                end
            else
                MovL(CPoint.MotionPoint[7], {a = LDAcc, v = LDVel, cp = 100}) -- 运动到抓取点上方
            end
        end
        Wait(Time.Pick.Post)
        if TransMotion(CPoint, Dir.Forward, LDAcc, LDVel) ~= true then
            return
        end
        for i = 1, CPoint.Paras.Times do
            if CPoint.Paras.Mode == MotionType.Part then
                -- 隔板放置：执行完最后一个过渡点后，直接直线滑到放置点。
                -- 这样可以减少多余上方点动作，并保持隔板进入托盘区域的方向一致。
                MovL(CPoint.MotionPoint[7 + i], {a = PlaceAcc, v = PlaceSpeed, cp = 100})
                CloseSucker(PalletNumber, CPoint, i)
                if SimulateMode == 1 then
                    UpdatePlaceBoxState(PalletNumber, CPoint)
                end

                -- 隔板放好后，先从当前放置点垂直抬升100mm，再进入回程过渡点
                local PartPlaceLift = GetPose()
                if (PartPlaceLift ~= nil) and (PartPlaceLift.pose ~= nil) then
                    PartPlaceLift.pose[3] = PartPlaceLift.pose[3] + PartPlaceLiftHeight
                    MovL(PartPlaceLift, {a = NLDAcc, v = NLDVel, cp = 100})
                end

                UpdateData(PalletNumber, CPoint)
                CheckPartitionRemainSensor(PalletNumber, CPoint)
            else
                if CPoint.Paras.SidePick == true then
                    if CPoint.Paras.OffSet[i] == 1 then
                        if SafeSideMovJ(CPoint.MotionPoint[15 + i], {a = LDAcc, v = LDVel, cp = 100}, true,
                            "approche point décalage dépose") ~= true then
                            return
                        end
                        if SafeSideMovL(CPoint.MotionPoint[11 + i], {a = PlaceAcc, v = PlaceSpeed, cp = 100}, true,
                            "approche au-dessus dépose") ~= true then
                            return
                        end
                    else
                        if SafeSideMovJ(CPoint.MotionPoint[11 + i], {a = LDAcc, v = LDVel, cp = 100}, true,
                            "approche au-dessus dépose") ~= true then
                            return
                        end
                    end
                    if SafeSideMovL(CPoint.MotionPoint[7 + i], {a = PlaceAcc, v = PlaceSpeed, cp = 100}, true,
                        "descente dépose") ~= true then
                        return
                    end
                else
                    if CPoint.Paras.OffSet[i] == 1 then
                        MovJ(CPoint.MotionPoint[15 + i], {a = LDAcc, v = LDVel, cp = 100})
                        MovL(CPoint.MotionPoint[11 + i], {a = PlaceAcc, v = PlaceSpeed, cp = 100})
                    else
                        MovJ(CPoint.MotionPoint[11 + i], {a = LDAcc, v = LDVel, cp = 100})
                    end
                    MovL(CPoint.MotionPoint[7 + i], {a = PlaceAcc, v = PlaceSpeed, cp = 100})
                end
                CloseSucker(PalletNumber, CPoint, i)
                if SimulateMode == 1 then
                    UpdatePlaceBoxState(PalletNumber, CPoint)
                end
                UpdateData(PalletNumber, CPoint)
                if CPoint.Paras.SidePick == true then
                    if SafeSideMovL(CPoint.MotionPoint[11 + i], {a = NLDAcc, v = NLDVel, cp = 100}, true,
                        "remontée au-dessus dépose") ~= true then
                        return
                    end
                    if (CPoint.Paras.Times ~= 1) and (CPoint.Paras.OffSet[i] == 1) then
                        if SafeSideMovL(CPoint.MotionPoint[15 + i], {a = NLDAcc, v = NLDVel, cp = 100}, true,
                            "retour point décalage dépose") ~= true then
                            return
                        end
                    end
                else
                    if CPoint.Paras.Times ~= 1 then
                        MovL(CPoint.MotionPoint[11 + i], {a = NLDAcc, v = NLDVel, cp = 100})
                        if CPoint.Paras.OffSet[i] == 1 then
                            MovL(CPoint.MotionPoint[15 + i], {a = NLDAcc, v = NLDVel, cp = 100})
                        end
                    else
                        MovL(CPoint.MotionPoint[11 + i], {a = NLDAcc, v = NLDVel, cp = 100})
                    end
                end
            end

        end
        local SkipStandby = false
        if CPoint.Paras.Mode == MotionType.Part then
            -- 隔板：放置后先走回程过渡点离开放置区域，再去安全点，最后回待机点
            if TransMotion(CPoint, Dir.Backward, NLDAcc, NLDVel) ~= true then
                return
            end
            PartitionGoSafePoint(CPoint)
        else
            if TransMotion(CPoint, Dir.Backward, NLDAcc, NLDVel) ~= true then
                return
            end

            -- 普通箱子：如果当前是每层最后一个box，下一笔队列就是隔板动作，
            -- 则不要再回取货待机点，直接去下一笔隔板动作的安全点，随后进入隔板逻辑
            local NextPartPoint = GetNextPartitionMotion(CQueue)
            if NextPartPoint ~= nil then
                if CPoint.Paras.SidePick == true then
                    local NextSafePoint = nil
                    if (NextPartPoint.MotionPoint ~= nil) and
                        (NextPartPoint.MotionPoint[7] ~= nil) and
                        (NextPartPoint.MotionPoint[7].joint ~= nil) then
                        NextSafePoint = DeepCopy(NextPartPoint.MotionPoint[7])
                    else
                        NextSafePoint = DeepCopy(PartSafePoint)
                    end

                    if SafeSideMovJ(NextSafePoint, {a = NLDAcc, v = NLDVel, cp = 100}, true,
                        "passage Side Pick vers sécurité intercalaire") ~= true then
                        return
                    end
                else
                    PartitionGoSafePoint(NextPartPoint, false, false)
                end
                SkipStandby = true
            end
        end
        CPose = GetPose()
        if SkipStandby == false then
            StandyMotion(PalletNumber, CPoint)
        end
    else
        -- 拆垛模式：从托盘取箱或取隔板，再放回输送线或取料点。
        if (SingleMotion == false) or (SyncSignal == true) or
            (StateMachine == FSMType.DLR and PalletNumber.Pallet ~= PrePallet) then
            if SingleMotion == false then
                SingleMotion = true
            else
                local Standy = {
                    pose = {}
                }
                Standy.pose = DeepCopy(CPoint.Paras.Standy.pose)
                Standy.pose[3] = Standy.pose[3] - CPoint.Paras.LH
                SafeMovJ(Standy, {a = NLDAcc, v = SyncMotionVel, cp = 100}, true)
            end
            SyncMotion(CPoint.Paras.LH)
        end
        TransMotion(CPoint, Dir.Forward, NLDAcc, NLDVel)
        for i = CPoint.Paras.Times, 1, -1 do
            if (CPoint.Paras.OffSet[i] == 1) then
                MovJ(CPoint.MotionPoint[15 + i], {a = NLDAcc, v = NLDVel, cp = 100}) -- 运动到放置过渡点
            end
            MovJ(CPoint.MotionPoint[11 + i], {a = NLDAcc, v = NLDVel, cp = 100}) -- 运动到放置点正上方
            MovL(CPoint.MotionPoint[7 + i], {a = NLDAcc, v = NLDVel, cp = 100})
            OpenSucker(PalletNumber, CPoint, i)
            if SimulateMode == 1 then
                UpdatePickBoxState(PalletNumber, CPoint)
            end
            UpdateData(PalletNumber, CPoint)
            MovL(CPoint.MotionPoint[11 + i], {a = LDAcc, v = LDVel, cp = 100}) -- 运动到放置点正上方
            if (CPoint.Paras.OffSet[i] == 1) then
                MovL(CPoint.MotionPoint[15 + i], {a = LDAcc, v = LDVel, cp = 100}) -- 运动到放置过渡点
            end
        end
        TransMotion(CPoint, Dir.Backward, LDAcc, LDVel)
        CPose = GetPose()
        SafeMovJ(CPoint.MotionPoint[7], {a = LDAcc, v = LDVel, cp = 100}, true)
        if (CPoint.Paras.Mode == MotionType.Part) then
            local CPartPick = GetAdjustedPartitionPoint(PalletNumber, PartPick)
            CPartPick.pose[3] = CPartPick.pose[3] - CPoint.Paras.LH + PalletNumber.ProcessNum.PartitionHeight *
                                    PalletNumber.Partition.RePartNum
            MovL(CPartPick, {a = NLDAcc, v = NLDVel, cp = 100}) -- 运动到抓取点
        else
            MovL(CPoint.MotionPoint[6], {a = LDAcc, v = LDVel, cp = 100}) -- 运动到抓取点
        end
        CloseSucker(PalletNumber, CPoint)
        if SimulateMode == 1 then
            UpdatePlaceBoxState(PalletNumber, CPoint)
        end
        if (CPoint.Paras.Mode == MotionType.Part) then
            SafeMovJ(CPoint.MotionPoint[7], {a = LDAcc, v = LDVel, cp = 100}, true)
        end
        StandyMotion(PalletNumber, CPoint)
    end
    UpdatePartData(PalletNumber, CPoint)
    PrePallet = PalletNumber.Pallet
    PrePoseHeight = CPose.pose[3] + CPoint.Paras.LH
end
---------------------------------------------------------------
-- 运动前处理。
-- 从队列中取出下一笔动作，并在真正执行前完成必要检查：
-- 1. 点位是否可达；
-- 2. 隔板动作开始前是否需要检查DI21余量传感器；
-- 3. 是否需要调整升降柱高度；
-- 4. 是否需要把当前动作模式写入隔板状态。
local function PreMotion(PalletNumber, CQueue)
    local CPoint = CQueue:Peek()
    if (CPoint == nil) then
        Alarm("Erreur du point PreMotion !", ErrorMessage.Type.PointErr)
        return nil
    end

    if (CPoint.Paras ~= nil) and (CPoint.Paras.Mode == MotionType.Part) then
        -- 隔板动作必须先检查DI21，再从队列Pop；避免隔板不足报警后动作被提前消费。
        -- For partition motion, check DI21 before Pop; otherwise an empty-magazine alarm may consume the queued partition motion.
        -- 这里不再先调用SyncPartitionRemainBySensor()，避免同一笔隔板动作前重复防抖等待。
        -- Do not call SyncPartitionRemainBySensor() here to avoid duplicate debounce before the same partition motion.
        if CheckPartitionRemainBeforeMotion(PalletNumber, CPoint) == false then
            return nil
        end
    end

    CPoint = CQueue:Pop()
    if (CPoint == nil) then
        Alarm("Erreur du point PreMotion !", ErrorMessage.Type.PointErr)
        return nil
    end

    if (CPoint.Paras.ErrIndex > 0) then
        GetPointInfo(PalletNumber, CPoint)
    end
    if (PalletNumber.Partition.Enable == true) then
        PalletNumber.Partition.Mode = CPoint.Paras.Mode
    end
    AdjustLiftingHeight(CPoint.Paras.LH)
    return CPoint
end
---------------------------------------------------------------
-- 执行运动队列。
-- 外层循环等待当前栈板仍然处于可运行状态；
-- 内层循环等待取料许可、缠膜完成、隔板动作许可等条件满足后，调用PTPMotion执行一次完整取放。
local function ExecuteMotion(PalletNumber, CQueue)
    while true do
        Wait(Time.Thread.s0)
        if (PalletNumber.State.Done == true or PalletNumber.Pallet ~= Pallet or Pallet == Idle) then
            break
        end
        if (CQueue:IsEmpty() == false) then
            local CPoint = PreMotion(PalletNumber, CQueue)
            if CPoint == nil then
                -- PreMotion may return nil when DI21 reports no partition before Pop. Keep the queue intact and retry after pause/recovery.
                Wait(Time.Thread.s0)
            else
                while true do
                    FilmMotion()
                    GetLiftingHeight(CPoint.Paras.LH)
                    -- 隔板动作不依赖输送线来料许可；普通箱子必须同时满足栈板就绪、取料信号就绪、缠膜完成。
                    if (CPoint.Paras.Mode == MotionType.Part) or
                        ((PalletNumber.State.StateReady == true) and (SignalReady == true) and (FilmDone == true)) then
                        LogInfo("La palette %s est en cours de traitement !", (Pallet == Left) and "gauche" or "droite")
                        SignalReady = false
                        PTPMotion(PalletNumber, CPoint, CQueue)
                        if (SignalReady == false) then
                            MotionDone = true
                        end
                        if (StateMachine == FSMType.DLR) then
                            return
                        else
                            break
                        end
                    end
                    Wait(Time.Thread.s0)
                end
            end
        end
    end
end
---------------------------------------------------------------
-- 获取运动状态
local function GetMotionFSM(PalletNumber, CQueue)
    if (PalletNumber.State.Init == true) then
        ExecuteMotion(PalletNumber, CQueue)
        if (SimulateMode == 1) or (AgingMode == 1) then
            if (StateMachine == FSMType.SLR or StateMachine == FSMType.DLR) then
                if FirstPallet.State.Done == true and SecondPallet.State.Done == true then
                    FirstPallet.State.SReset = true
                end
            else
                PalletNumber.State.SReset = true
            end
        end
    end
end
---------------------------------------------------------------
-- 主状态机调度。
-- 单输送模式下直接执行当前Pallet对应队列；
-- 双输送模式下只有SignalReady为true时才调度，避免两个队列同时抢占机器人。
local function MotionFSM()
    local SwitchFSM = {
        [Idle] = function()
        end,
        [Left] = function()
            GetMotionFSM(FirstPallet, FQueue)
        end,
        [Right] = function()
            GetMotionFSM(SecondPallet, SQueue)
        end
    }

    if (StateMachine ~= FSMType.DLR) or (StateMachine == FSMType.DLR and SignalReady == true) then
        local switch_mode = SwitchFSM[Pallet]
        if switch_mode then
            switch_mode()
        else
            Alarm("SwitchFSM est incorrect !", ErrorMessage.Type.WorkingDataErr)
        end
    end
end
---------------------------------------------------------------
---------------------------------------------------------------
-- 主程序
InitStorageMode()
InitModbus()
-- 必须在InitFSM/ACK/隔板不足判断前同步，否则界面和报警逻辑仍可能读取到旧的0。
SyncAllPartitionRemainBySensor(true)
InitFSM()
InitPallet()
while true do
    Wait(Time.Thread.s0)
    MotionFSM()
end
